/* 一周一题 · 第 2 题《军服的变色：五常军装三百年》内容数据
 * 事实来源见 REFS；每条都经过至少两个独立来源比对，只有一个来源或说法不一的，标“中 / 低”并写出分歧。
 * 颜色十六进制值是依据文字描述与彩照估出的绘图近似值，不是色卡实测。
 */
window.UDATA = (function () {
  var ERAS = [
    { k: 'E1', name: '线列时代', range: 'c.1700–1815', a: 1700, b: 1815 },
    { k: 'E2', name: '民族国家与殖民', range: '1815–1899', a: 1815, b: 1900 },
    { k: 'E3', name: '世纪之交与一战', range: '1900–1918', a: 1900, b: 1919 },
    { k: 'E4', name: '战间期与二战', range: '1919–1945', a: 1919, b: 1946 },
    { k: 'E5', name: '冷战前期', range: '1946–1965', a: 1946, b: 1966 },
    { k: 'E6', name: '冷战后期', range: '1966–1990', a: 1966, b: 1991 },
    { k: 'E7', name: '数码与全球化', range: '1991–2010', a: 1991, b: 2011 },
    { k: 'E8', name: '体系化与防护', range: '2011–今', a: 2011, b: 2026 }
  ];
  var COUNTRIES = [
    { k: 'cn', name: '中国', long: '中国（清军 → 新军 → 国民革命军 / 红军 → 解放军）', short: '中' },
    { k: 'us', name: '美国', long: '美国（大陆军 → 美国陆军，兼及海军陆战队）', short: '美' },
    { k: 'ru', name: '俄 / 苏', long: '俄罗斯 / 苏联（帝俄 → 红军 / 苏军 → 俄罗斯联邦）', short: '俄' },
    { k: 'uk', name: '英国', long: '英国（British Army，兼及近卫师仪仗）', short: '英' },
    { k: 'fr', name: '法国', long: '法国（Armée de terre，兼及圣西尔与外籍军团）', short: '法' }
  ];

  /* 四类服装：页面自己的归类，并列出各国官方叫法 */
  var CATS = [
    { k: 'dress', name: '礼服', def: '含仪仗礼服：阅兵、典礼、国事活动穿的最高等级服装，保留颜色与传统。',
      names: { cn: '礼服；仪仗队为“礼宾服”', us: 'Army Service Uniform（蓝，今作礼服）、Mess Dress；陆战队 Dress Blues', ru: 'парадная（队列 / 非队列两套）；仪仗队专用“особая церемониальная парадная”', uk: 'Full Dress（全礼服，近卫师等公费）＋ No.1 Dress', fr: 'tenue de tradition / historique（俗称 grande tenue；圣西尔称 GU）' } },
    { k: 'service', name: '常服', def: '日常办公、外出与一般正式场合的“职业装”。',
      names: { cn: '常服；21 式另有夹克式“作业服”', us: 'Army Green Service Uniform（AGSU，Class A / B）', ru: 'повседневная', uk: 'No.2 Dress（Service Dress，卡其）', fr: 'tenue de cérémonie / tenue de service courant（外出服俗称 tenue de sortie）' } },
    { k: 'training', name: '作训服', def: '训练、执勤与日常勤务穿的作业服。',
      names: { cn: '作训服（1987 年起单列）', us: 'Army Combat Uniform（ACU，OCP 图案）', ru: '无独立类别：条例明文训练课、演习穿 полевая', uk: 'No.13 / No.14 营房服；野外训练穿 No.8', fr: '未单列：训练穿作战服 treillis' } },
    { k: 'combat', name: '作战服', def: '真正上战场的一套：作训服或野战服，加上头盔、护甲与携行具。',
      names: { cn: '官方不单列（2025 年版《内务条令》无“作战服”一词），即作训服 + 头盔 / 护甲', us: '不单列：ACU + 头盔、防弹衣', ru: 'полевая（野战服）+ Ratnik 单兵装备', uk: 'No.8 Combat Dress（今 PCS-CU，MTP 图案）', fr: 'tenue de combat（treillis）' } }
  ];

  var TAGS = {
    culture: { name: '文化', desc: '传统、审美、身份认同' },
    politics: { name: '政治', desc: '政权、意识形态、国家象征' },
    combat: { name: '实战', desc: '隐蔽、识别、防护与战场经验' },
    tech: { name: '技术', desc: '染料、纤维、材料与制造' }
  };

  /* ---------- 40 个格子：每国每个时代一套“代表性军服” ----------
   * fig：示意图参数（preset + 覆盖）；fig2：第二套示意（礼服 / 常服或前后对照）
   * photos：真实图片（assets/ 里的文件名，图注见 IMAGES）
   */
  var CELLS = {
    cn: {
      E1: { name: '八旗大阅甲胄', year: '清前中期；大阅顺治时定为三年一次',
        dress: '大阅甲：乾隆御用棉甲为明黄缎面、满布金帽钉、黑绒镶边，胸前悬护心镜，“主要用于大阅”。',
        service: '—（无区分；兵丁平日穿号衣）', training: '—', combat: '甲胄分藤、皮、棉、铁甲，是“作战或礼仪用服装”；到清中后期多用于礼仪。',
        colors: [['#E8B800', '明黄缎'], ['#1A1A1A', '黑绒边']],
        why: '大阅是皇帝检阅八旗的国家典礼，甲胄的颜色与金钉首先是等级与皇权的视觉符号。',
        dispute: '“八旗兵甲按本旗颜色”是通行说法，但本轮没有取得两个来源，不写。',
        conf: '中', confNote: '大阅甲的用途：高（故宫藏品说明）；清中后期礼仪化：仅一处来源。',
        refs: ['cn18'], fig: null, figNote: '本格不画示意图：甲胄形制复杂，用郎世宁画作代替。', photos: ['cn-1739-qianlong-ceremonial-armour-castiglione.jpg'] },
      E2: { name: '号衣（勇营 / 八旗兵丁）', year: '19 世纪；1895 年起转向西式',
        dress: '—（沿用传统礼服与甲胄，没有近代意义的分类）', service: '—', training: '—',
        combat: '行褂外罩马褂或马甲，前胸后背各缝一块圆布，写部队番号或主帅姓氏；湘淮勇营缀“勇”字号补，注明营号与姓名；中长宽口裤，外系三角战裙，颜色醒目。1895 年新建陆军聘德国教官、按德国条令操练，开始用肩章标番号。',
        colors: [['#2B3B5C', '号衣（示意色，因营而异）'], ['#F2EFE6', '圆补'], ['#B33A2E', '镶边（示意）']],
        why: '圆补就是“谁的兵、哪个营”的识别牌——在旗号、火绳枪与冷兵器混用的战场上，醒目比隐蔽更要紧。',
        dispute: '绿营号衣写“兵”字是常见说法，本轮未能核实；图中写“勇”字，依据是勇营的记载。',
        conf: '中', confNote: '号衣形制主要依据一篇引用原始公报的论文；新建陆军的德国教官与条令：高。',
        refs: ['cn9', 'cn19', 'cn24'],
        fig: { preset: 'qing1860', badge: { chest: 'char:勇' }, headgear: { type: 'qing', warm: true } },
        figNote: '示意图：号衣颜色因营而异，此处取蓝袍红边、暖帽；依据：胡彦青、张竞琼 2017〔中9〕及 John Thomson 照片。',
        photos: ['cn-1874-qing-soldier-haoyi-thomson.jpg'] },
      E3: { name: '新军军服（练兵处奏定《陆军服制》）', year: '1905 年奏定；1912 年北洋《陆军服制》',
        dress: '1905 年“大礼服仍遵旧制”，礼服仍戴翎顶；1910 年禁卫军服制才“抛弃朝冠，改用军帽”；北洋礼服为欧式（近德式），只给尉官以上。',
        service: '西式立领单排扣短上衣、硬檐军帽；冬用深蓝、夏用土黄；“三等九级”军衔用领章、肩章、袖章表示，领章按兵科分色；北洋常服为茶青色，式样与徽章“基本照搬日本陆军”。',
        training: '—（无区分）', combat: '同常服，没有钢盔。',
        colors: [['#2B3A55', '冬常服深蓝'], ['#B8995A', '夏常服土黄'], ['#5A6470', '北洋茶青（实物多偏蓝灰）']],
        why: '号衣“华丽的颜色与前后的圆布，刚好成为敌人瞄准的靶子”，西式窄身军服便于洋操的分合进退；洋兵以“服章不辨”为由不向华官敬礼，于是要“各按等级次第，分设记号”。礼服保留翎顶，则是向皇权礼制的妥协。',
        dispute: '取法德国还是日本？同一篇论文两说并存；樊学庆认为 1905 年正式款同时受日本陆军 1904 年战时服与驻津德军夏季野战服影响——本页写作“日、德双重来源”。',
        conf: '中', confNote: '1905、1912 两次服制主要依据一篇引用《政艺通报》《安徽公报》原文的论文，第二份独立来源未能取得全文。',
        refs: ['cn9', 'cn19', 'cn24'],
        fig: { headgear: { type: 'peaked', color: '#2B3A55', band: '#2B3A55', badge: '#c9a646' }, coat: { cut: 'service-closed', color: '#2B3A55' }, collar: 'standing', collarTabs: '#b33a2e', buttons: { n: 5, color: '#c9a646' }, belt: '#1d1b18', beltBuckle: '#a4a494', pouches: '#1d1b18', trousers: { color: '#2B3A55', style: 'puttees' }, puttees: '#e6e1d3', footwear: '#1d1b18' },
        fig2: { title: '夏常服（土黄）', headgear: { type: 'peaked', color: '#B8995A', band: '#B8995A', badge: '#c9a646' }, coat: { cut: 'service-closed', color: '#B8995A' }, collar: 'standing', collarTabs: '#b33a2e', buttons: { n: 5, color: '#c9a646' }, belt: '#1d1b18', trousers: { color: '#B8995A', style: 'puttees' }, puttees: '#B8995A', footwear: '#1d1b18' },
        figNote: '示意图：领章颜色按兵科而异，此处取红色示意；依据：胡彦青、张竞琼 2017〔中9〕与 1911 年成都新军照片。',
        photos: ['cn-1911-new-army-chengdu-knight.jpg'] },
      E4: { name: '国民革命军军常服 + M35 钢盔', year: '1929、1930、1936 年三次颁行服制条例；德械师 1930 年代中期',
        dress: '大礼服：1929 年一版为蓝色，1936 年一版为黑色。',
        service: '立翻领中山装式四袋上衣：1929 年为灰色，1936 年改草黄；领章按兵科分色（步兵红、骑兵黄、炮兵蓝），缀 1–3 颗三角星；北伐时的大盘帽被德国顾问设计的圆顶加围布帽取代。',
        training: '—（无区分）',
        combat: '军常服 + 钢盔：约 20 个“调整师”（德械师）配德制 M35，进口 30 余万顶（另一说 31.5 万）；其他部队用英式、法式盔或没有钢盔，绑腿、草鞋。红军：1929 年长汀统一灰军装，1932 年后定型为灰色中山装式上衣 + 八角帽 + 红五星 + 红领章；1937 年起八路军、新四军改穿国军灰布军服，以臂章区别。',
        colors: [['#6E7275', '1929 年灰'], ['#9C8F5E', '1936 年草黄'], ['#5F6B78', '冬装蓝灰']],
        why: '北伐统一后要统一各派系的军服；以德国为师的军事现代化带来了顾问、德式帽与 M35；草黄、土黄“与野战条件的自然色更加接近”；条例还规定原料一律国产。',
        dispute: '“改草黄出自德国顾问建议”只有单一弱来源，未采用；M35 进口数两个数字相近，可能同源。',
        conf: '中–高', confNote: '条例年份：高（两个来源）；月日另有说法。',
        refs: ['cn9', 'cn10', 'cn11', 'cn1', 'cn2', 'cn16'],
        fig: { headgear: { type: 'm35', color: '#5f6352' }, coat: { cut: 'service-closed', color: '#9C8F5E' }, collar: 'turndown', collarTabs: '#b33a2e', buttons: { n: 5, color: '#6b6242' }, belt: '#5a3d24', beltBuckle: '#a4a494', pouches: '#5a3d24', trousers: { color: '#9C8F5E', style: 'puttees' }, puttees: '#9C8F5E', footwear: '#c9b27a', weapon: 'rifle' },
        fig2: { title: '红军（1932 年后）', headgear: { type: 'cap8', color: '#6E7275', badge: 'star' }, coat: { cut: 'service-closed', color: '#6E7275' }, collar: 'turndown', collarTabs: '#c8102e', buttons: { n: 5, color: '#55585a' }, trousers: { color: '#6E7275', style: 'puttees' }, puttees: '#6E7275', footwear: '#1d1b18' },
        figNote: '示意图：M35 钢盔左侧的青天白日徽从正面看不到；草鞋用浅色示意。依据：〔中10〕〔中11〕〔中16〕。',
        photos: ['cn-1942-nra-m35-helmet-signal-corps.jpg', 'cn-1937-eighth-route-army-sentry-great-wall-shafei.jpg'] },
      E5: { name: '55 式军服（授衔）', year: '1955-09-16 国务院批准，10-01 起实行；1958 年两次修改',
        dress: '礼服配校官以上军官和仪仗队、军乐团：纯毛华达呢，元帅与陆空军将校官为海蓝色，配白衬衣、藏青领带，衔级靠领边、袖头、裤缝饰物区分；1956-09-30 仪仗队第一次统一穿礼服。',
        service: '军官：军衔肩章 + 军种领章 + 大檐帽 + 圆形“八一”帽徽；士兵：军衔领章 + 船形帽；陆军棕绿。1958 年修改：平时军官只佩领章、戴解放帽，“便于操练和劳动”；士兵船形帽 1958 年决定、1959 年换发夏服时改为解放帽。',
        training: '—（55 式另有“工作服”）', combat: '同常服（抗美援朝时志愿军夏服在肘、肩、臀、膝加一层布）。',
        colors: [['#6B6A3F', '陆军棕绿'], ['#1F3A5F', '礼服海蓝'], ['#C8102E', '领章与帽徽红']],
        why: '正规化需要军衔标识：军衔“主要参照苏联”，但不照搬兵种元帅等设置；1956 年总参文件承认新服装“部分地采用了苏联和各人民民主国家及国际上通用的”样式。士兵帽不设帽檐，是因为帽檐“卧射时妨碍视线”，而且船形帽便于戴钢盔。',
        dispute: '55 式是“礼服、常服”两类还是另加“工作服”三类，官方叙述不一；“1958 年起礼服停穿”未能核实。',
        conf: '高', refs: ['cn12', 'cn13', 'cn14', 'cn2', 'cn23', 'cn1'],
        fig: { headgear: { type: 'sidecap', color: '#6B6A3F', badge: 'star' }, coat: { cut: 'service-closed', color: '#6B6A3F' }, collar: 'turndown', collarTabs: '#c8102e', buttons: { n: 5, color: '#55542f' }, belt: '#5a3d24', trousers: { color: '#6B6A3F' }, footwear: '#1d1b18' },
        fig2: { title: '军官常服', headgear: { type: 'peaked', color: '#6B6A3F', band: '#b22a2a', badge: '#c9a646' }, coat: { cut: 'service-closed', color: '#6B6A3F' }, collar: 'turndown', shoulder: 'boards', shoulderColor: '#c9a646', buttons: { n: 5, color: '#c9a646' }, trousers: { color: '#6B6A3F' }, footwear: '#1d1b18' },
        figNote: '示意图：士兵戴船形帽、佩军衔领章（领章细节从略）；军官肩章颜色为示意。依据：〔中2〕〔中12〕〔中13〕。',
        photos: ['cn-1955-type55-marshal-greatcoat-peng-dehuai.jpg'] },
      E6: { name: '65 式“三点红” → 87 式', year: '1965-06-01 取消军衔；1985-05-01 换 85 式；1988-10-01 恢复军衔、装备 87 式',
        dress: '1965–约 1984 年三军仪仗队没有礼服；87 式设计了西服式礼服，但受经费所限没有装备部队。',
        service: '65 式：官兵一律戴解放帽，佩全红五星帽徽 + 全红领章，干部四个口袋、战士两个口袋；71 / 78 式改用化纤混纺以减重；85 式恢复大檐帽与军种肩章、领章；87 式军官夏常服翻领，配米黄衬衣、藏青领带。',
        training: '87 式首次单列作训服：夏、冬作训服与冬、夏迷彩作训服共 4 种。',
        combat: '作训服 + 钢盔（型号未核，不写）；87 式迷彩为林地型斑块，受北约 1980 年代初“三色丛林迷彩”启发。',
        colors: [['#707A45', '65 / 78 式草绿'], ['#C8102E', '红星与红领章'], ['#5E5B3B', '87 式常服橄榄棕绿']],
        why: '1965 年的决定原文只有一句“取消中国人民解放军军衔制度”；官兵差别被压缩到口袋数量，红星、红领章回到 1929 年红军的符号（本页解读）。改革开放后，“体制单一、样式呆板、面料落后”成了问题：87 式研究了 27 个国家的军服，测量了 1.5 万名官兵的体型。',
        dispute: '“一颗红星头上戴，革命红旗挂两边”是流传的俗语，出处未能核实；“的确良”的官方用例未见。',
        conf: '高（事实）/ 中（解读）', refs: ['cn1', 'cn2', 'cn5', 'cn14', 'cn15', 'cn23'],
        fig: { preset: 'cn1965', coat: { cut: 'service-closed', color: '#707A45' }, headgear: { type: 'cap', color: '#707A45', badge: 'star' }, trousers: { color: '#707A45' } },
        fig2: { title: '87 式迷彩作训服', headgear: { type: 'cap', cover: 'camo' }, coat: { cut: 'field' }, camo: { type: 'woodland', colors: ['#8b8a5c', '#4d5b33', '#5b4632', '#2a2a22'], seed: 7 }, buttons: { color: '#3a3a2a' }, belt: '#4a4a36', trousers: { style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：65 式为解放帽 + 红五星 + 红领章；87 式迷彩只画“林地斑块”类型，不复刻具体图案。依据：〔中1〕〔中2〕〔中5〕。',
        photos: ['cn-1972-type65-honor-guard-nixon-whitehouse.jpg', 'cn-1998-type87-general-zhang-wannian-dod.jpg'] },
      E7: { name: '07 式军服', year: '2007-07-03 发放仪式；08-01 起全军陆续换发，计划 3 年完成',
        dress: '军官礼服：双排扣队列礼服，只配军官、四季通用，理由是“穿着时机少，制作成本高”；仪仗队礼宾服与 07 式军官礼服基本统一。',
        service: '陆军松枝绿、海军深藏青（夏为白）、空军蓝灰；陆空军春秋常服为收腰“猎装式”，军官冬常服由关门领改开领；新增姓名牌、级别资历章、胸标、臂章；夏常服配贝雷帽（2000–2017）。',
        training: '07 式数码迷彩作训服：自主知识产权的像素迷彩，先后列装林地、荒漠、海洋等品种，按军种而非地形配发；夏作训服由夹克式改为散摆式。',
        combat: '作训服 + 头盔与携行具（官方不单列“作战服”）。',
        colors: [['#4F5A45', '陆军松枝绿'], ['#1C2541', '海军深藏青'], ['#50607A', '空军蓝灰']],
        why: '松枝绿在绿色里“加入了红军、八路军军服的灰色调”，按东方人肤色从几十种冷绿中筛出，并与国内行业制服拉开区别；海军西服式双排扣常服、衔级标在袖口，“便于舰上识别和国际交往”。4 个系列 644 个品种，被称为“我军历史上最大规模的换装”。',
        dispute: '07 式数码迷彩的品种：只有一处列出“林地、荒漠、海洋等”，常见的“城市”“丛林”说法没有找到官方来源。',
        conf: '高', refs: ['cn2', 'cn3', 'cn4', 'cn5', 'cn23'],
        fig: { preset: 'cn2007' },
        fig2: { title: '陆军春秋常服（松枝绿）', headgear: { type: 'peaked', color: '#4F5A45', band: '#4F5A45', badge: '#c9a646' }, coat: { cut: 'service', color: '#4F5A45' }, collar: 'open-tie', shirt: '#d9d2bd', tie: '#3a4232', shoulder: 'boards', shoulderColor: '#4F5A45', buttons: { n: 4, color: '#c9a646' }, trousers: { color: '#4F5A45' }, footwear: '#1d1b18' },
        figNote: '示意图：数码迷彩只画“像素”类型，不复刻 07 式具体图案。依据：〔中3〕〔中4〕〔中5〕。',
        photos: ['cn-2015-type07-digital-camo-dme-army.jpg'] },
      E8: { name: '21 式作训服（“星空迷彩”）与作业服', year: '2019-10-01 阅兵亮相；2021 年冬起全军陆续换发',
        dress: '2014 年三军仪仗队启用新式礼宾服（春秋、夏、冬三类 18 个品种）：袖头绣人字形橄榄枝加星徽，腰带改金黄色，臂章改红色并加军旗标志，大檐帽加高帽墙。',
        service: '常服沿用 07 式体系（2015–16 年换发新臂章、胸标，2017-08-01 取消贝雷帽）；21 式新增夹克式“作业服”，用于办公等日常场合。',
        training: '21 式迷彩作训服（丛林、荒漠等）+ 特勤作训服（舰艇、空勤、地勤）+ 作战靴；按“备战优先、急用先发”先发迷彩和特勤作训服。',
        combat: '作训服 + 头盔、防弹衣与携行具；迷彩按作战地形而非军种配发，军衔、姓名贴、胸标改为迷彩底的低可视度标志；立领防尘、斜插口袋。',
        colors: [['#5E6B45', '丛林型绿'], ['#6E5A3E', '褐'], ['#23261E', '黑'], ['#A8A27A', '浅色“星点”']],
        why: '官方评论承认 07 式迷彩“过于强调军种区别”：海军陆战队在朱日和的荒漠演习仍穿海洋迷彩，标志醒目。21 式因此改为按地形配发、格子更细、颜色更自然，并降低标志的可视度。',
        dispute: '品种数：官方只说“丛林、荒漠等”，评论文章称五种。“星空迷彩”“作战服”都是媒体叫法——2025 年版《内务条令》只有作训服、常服、作业服、礼服、礼宾服，没有“作战服”一词。',
        conf: '高', refs: ['cn5', 'cn6', 'cn7', 'cn8', 'cn20', 'cn22', 'cn23'],
        fig: { headgear: { type: 'modern', cover: 'camo' }, coat: { cut: 'combat-shirt' }, camo: { type: 'digital', colors: ['#5E6B45', '#6E5A3E', '#23261E', '#A8A27A', '#3f4a30'], seed: 21, scale: 0.7 }, belt: '#4a4a36', trousers: { style: 'bloused' }, footwear: '#3a3024' },
        figNote: '示意图：只画“细像素数码”类型，不复刻 21 式具体图案。依据：〔中5〕〔中6〕〔中7〕。',
        photos: ['cn-2025-type21-marines-cns.jpg', 'cn-2021-type21-xingkong-blouse-cc0.jpg', 'cn-2024-honor-guard-battalion-kremlin.jpg'] }
    },

    us: {
      E1: { name: '大陆军蓝色团服', year: '1779-10-02 华盛顿总命令',
        dress: '—（一套团服兼作阅兵与作战）', service: '—', training: '—',
        combat: '蓝上衣 + 按州分区的饰面色：新英格兰各州白，纽约、新泽西浅黄（buff），宾夕法尼亚至弗吉尼亚红，南部三州蓝；炮兵猩红饰面、黄铜扣。白或浅黄马甲马裤，黑三角帽。1782 年起步兵饰面统一为红色。',
        colors: [['#1F2F4F', '大陆军蓝'], ['#A3232B', '红饰面'], ['#D8C08A', '浅黄 buff'], ['#F2F0E6', '白']],
        why: '一是要与英军“红衫”区分；二是顺着供货走——1775 年定的棕色因缺布名存实亡，1778 年法国援助的成衣本就是蓝、棕两色，1779 年又向法国订购军服物资；华盛顿本人自 1775 年就穿“蓝 + 浅黄”。',
        dispute: '步兵统一红饰面的年份：NARA 作 1782，陆军军史中心摘录作 1779；“辉格党政治色”“北美靛蓝产量”等流行解释未见官方来源。',
        conf: '高（条令）/ 中（动机）', refs: ['us1', 'us2', 'us3', 'us4'],
        fig: { preset: 'us1779' }, figNote: '示意图：取宾夕法尼亚至弗吉尼亚一组的红饰面；依据：1779 年总命令原文〔美1〕。',
        photos: ['us-1781-continental-mcbarron.jpg'] },
      E2: { name: '联邦军 sack coat + 天蓝裤', year: '1850 年代–1865；天蓝裤 1833 年定制（另说 1832）',
        dress: '1851 年条例以长礼服外套（frock coat）为勤务服并建立兵种色；1858 年黑毡“Hardee 帽”用于礼仪场合。',
        service: 'frock coat + 便帽。', training: '—（fatigue 用的 sack coat 本身就是劳作 / 野战服）',
        combat: '深蓝法兰绒 sack coat（4 粒铜扣）+ 天蓝羊毛裤 + 软顶便帽（形近法式 kepi）；邦联军为灰色或胡桃褐（butternut）短夹克。1872 年野战改穿褶裥“瑞士罩衫”，1898 年美西战争采用仿英式卡其布野战服。',
        colors: [['#1C2841', '联邦深蓝'], ['#8DA9C4', '天蓝裤'], ['#8C8F8A', '邦联灰'], ['#9B7B4B', '胡桃褐']],
        why: '蓝色延续大陆军的“祖色”；1850 年代的 frock coat 与 kepi 式便帽明显借鉴法国，南北战争中甚至有部队直接进口法国猎兵服。',
        dispute: '1851 / 1858 / 1872 条例年份只在陆军军史中心的调查里一手核到（中）；“1851 款受法国影响”有博物馆与百科两处说法（中）。',
        conf: '高（颜色）/ 中（条例年份）', refs: ['us2', 'us9', 'us10', 'us5', 'fr27'],
        fig: { preset: 'us1863' }, figNote: '示意图：依据 CivilWar@Smithsonian〔美9〕与 Ogden 1890 年图版。',
        photos: ['us-1862-union-campaign-uniform-ogden.jpg'] },
      E3: { name: '橄榄褐立领勤务服 + M1917 钢盔', year: '1902 年条例；1917 年美国远征军',
        dress: '1902 年后蓝色只保留为礼服。',
        service: '橄榄褐（OD）羊毛立领勤务外套（冬）/ 卡其布（夏）；1911 年“蒙大拿折顶”宽檐帽。',
        training: '粗布劳作服（型号未核）。',
        combat: 'OD 羊毛立领外套 + 马裤 + 螺旋绑腿 + M1917 钢盔（英国 Brodie Mark I 的美制变体）。',
        colors: [['#5F5B3C', '橄榄褐 OD'], ['#C3B091', '卡其'], ['#4B5320', '钢盔橄榄']],
        why: '陆军军史中心把 1898 年的卡其野战服直接记为“基于英国样式”；此后“礼服保留传统蓝、野战用土色”的二分法延续至今。',
        conf: '高', refs: ['us2', 'us5', 'us6'],
        fig: { headgear: { type: 'brodie', color: '#4B5320' }, coat: { cut: 'service-closed', color: '#5F5B3C' }, collar: 'standing', buttons: { n: 5, color: '#6b6242' }, belt: '#8a7f5a', beltBuckle: '#8a8778', pouches: '#8a7f5a', trousers: { color: '#5F5B3C', style: 'puttees' }, puttees: '#5F5B3C', footwear: '#5a3a24', weapon: 'rifle' },
        figNote: '示意图：依据〔美2〕〔美6〕与 1918 年通信兵照片。',
        photos: ['us-1918-american-soldiers-brodie-signalcorps.jpg'] },
      E4: { name: 'M1 钢盔 + M-1943 分层野战服', year: 'M1 钢盔 1941；M-1943 1943 年研制，欧洲战区 1944-11-10 才接受',
        dress: '战时基本不穿蓝礼服（“1937 年恢复”仅一处来源）。',
        service: '军官“Greens”：深橄榄绿上衣 + 浅褐偏粉长裤（俗称 pinks and greens）；士兵 OD 羊毛开领上衣 + 衬衫领带。',
        training: '人字纹斜纹布（HBT）工作服。',
        combat: 'M1 钢盔 + M-1943 体系：羊毛内衣、毛衬衫、高领毛衣、夹克、防风外套逐层叠穿；1944 年年中启用短款 M-1944 羊毛野战夹克（“Ike jacket”）。',
        colors: [['#4E4B33', 'M-1943 外套'], ['#3E3B2A', '军官 greens'], ['#B4A28C', '“pinks”长裤'], ['#4B5320', 'M1 钢盔']],
        why: '分层可以按气温增减，替代笨重的大衣；但欧洲战区起初拒绝换装，物资“来得太晚，赶不上那个冬天”，冻伤成了官方医疗战史的专章。Ike 夹克仿英国 Battledress 短上衣以省布，并受艾森豪威尔偏好的定制短夹克影响。',
        conf: '高', refs: ['us15', 'us13', 'us6', 'us12', 'us10'],
        fig: { preset: 'us1944' }, figNote: '示意图：依据〔美13〕〔美15〕。',
        photos: ['us-1944-ike-jacket-101st-dday.jpg'] },
      E5: { name: 'Army Green 常服 + OG 作训服', year: '1954 年批准 Army Green（一直穿到 2015-10-01）',
        dress: 'Army Blue（深蓝上衣 + 浅蓝裤；“1957 年恢复”仅一处来源）。',
        service: 'Army Green：开领单排 4 扣、四个口袋，配衬衫与领带，大檐帽或船形帽。',
        training: '棉缎 OG-107 作训服（“1952 年采用”未能核实）。',
        combat: 'M1 钢盔 + OG 作训服 / 野战夹克。',
        colors: [['#3D4431', 'Army Green'], ['#5C5F3B', 'OG 橄榄绿'], ['#1F2A44', 'Army Blue']],
        why: '二战后大量剩余 OD 军服流入民间，“平民甚至罪犯”都在穿，1954 年陆军人事官员指出 OD 已失去军人的威望——新的绿色用来重建职业形象。',
        dispute: '“与 1947 年独立的空军蓝制服区分”之说未能核实。',
        conf: '中', refs: ['us14', 'us5'],
        fig: { headgear: { type: 'm1', color: '#4B5320' }, coat: { cut: 'field', color: '#5C5F3B' }, buttons: { color: '#3a3a2a' }, belt: '#7a7458', trousers: { color: '#5C5F3B', style: 'bloused' }, footwear: '#1d1b18' },
        fig2: { title: 'Army Green 常服', headgear: { type: 'peaked', color: '#3D4431', band: '#3D4431', badge: '#c9a646' }, coat: { cut: 'service', color: '#3D4431' }, collar: 'open-tie', shirt: '#c8b48f', tie: '#1d1b18', buttons: { n: 4, color: '#c9a646' }, trousers: { color: '#3D4431' }, footwear: '#1d1b18' },
        figNote: '示意图：依据〔美5〕〔美14〕。',
        photos: ['us-1968-og107-mp-vietnam.jpg'] },
      E6: { name: 'BDU + M81 林地迷彩 + PASGT 头盔', year: '1981-10-01 起全军配发 BDU；PASGT 1983 年格林纳达首次实战',
        dress: 'Army Blue。', service: 'Army Green（Class A / B）。',
        training: 'BDU 林地迷彩：1981 年后作训与野战合一（此前为 OG-107）。',
        combat: 'BDU + PASGT 凯夫拉头盔（外形像二战德军钢盔，士兵称“Fritz”）；沙漠用六色“巧克力片”DBDU。',
        colors: [['#8A9A5B', '浅绿'], ['#6B4E31', '棕'], ['#3B4A2C', '深绿'], ['#1C1C1C', '黑']],
        why: '迷彩从越战时的特种部队装备，变成全军驻地与野战一体的日常服；凯夫拉取代钢，头盔轮廓向护得更多的“德式”靠拢——但来源只说“形似”，没有证据表明有意借鉴。',
        dispute: 'ERDL“1948 年设计、1967–68 年越南配发”与“M81 由 ERDL 放大而来”本轮未能核实，未写入。',
        conf: '中（BDU 年份经百科转引官方年鉴）/ 高（PASGT）', refs: ['us18', 'us5', 'us11', 'us6'],
        fig: { preset: 'us1985' }, figNote: '示意图：只画“林地大斑块”类型。依据：〔美11〕〔美18〕。',
        photos: ['us-1985-m81-woodland-bdu-teamspirit.jpg', 'us-1969-erdl-tigerstripe-rangers.jpg'] },
      E7: { name: 'ACU + UCP 通用迷彩；陆战队 MARPAT', year: 'UCP 色样 2004-07；2005–08 年替换 BDU；MARPAT 2002-01 亮相',
        dress: 'Army Service Uniform（蓝）：2006 年宣布，2010 年成为标准配发，2010–2015 年兼作唯一常服。',
        service: 'Army Green → ASU（Army Green 最后穿着日延至 2015 年）。',
        training: 'ACU（UCP 灰色像素迷彩）；沙漠地区用三色 DCU（“1992 年引入”仅一处来源）。',
        combat: 'ACU + ACH 先进战斗头盔（2003 年推出）+ 防弹背心；2010 年起阿富汗部队改穿 OEF-CP（即 MultiCam）。',
        colors: [['#C2B8A3', 'Desert Sand'], ['#8A8D8F', 'Urban Gray'], ['#6E7B63', 'Foliage Green']],
        why: 'UCP 想用一种灰绿图案“通吃”所有地形，结果在阿富汗暴露局限——2009 年国会在补充拨款法中要求提供“适合当地环境的迷彩”。海军陆战队的 MARPAT 以加拿大 CADPAT 为基础，图案由政府申请专利、禁止商售，迷彩同时成了军种的识别标志。',
        dispute: '媒体常引“UCP 花费约 50 亿美元”，本轮没有官方来源，未写入；GAO-12-707 报告原文未能读取。',
        conf: '高（2009–10 换迷彩）/ 中（MARPAT、ACU 年份）', refs: ['us7', 'us8', 'us17', 'us18', 'us14', 'us3', 'us6'],
        fig: { preset: 'us2008' }, figNote: '示意图：只画“灰色像素”类型，不复刻 UCP / MARPAT 具体图案。依据：〔美7〕〔美8〕。',
        photos: ['us-2004-acu-ucp-peo-soldier.jpg', 'us-2012-usmc-marpat-desert.jpg'] },
      E8: { name: 'OCP 作战服 + AGSU“陆军绿”常服', year: 'OCP 2015-07-01 起配发，UCP 2019-10-01 退役；AGSU 2018-11 宣布',
        dress: 'ASU（蓝）回归礼服：阅兵、检阅与典礼。',
        service: 'AGSU：“pinks and greens”复刻——深橄榄上衣 + 浅褐偏粉长裤；2027-10-01 为强制持有日。',
        training: 'OCP 图案 ACU；配套改为 tan 499 T 恤与狼棕色靴；2019 年起推出热带作战服 IHWCU。',
        combat: 'OCP ACU + 头盔、防弹衣；空军 2018 年决定改穿陆军 OCP，2021-04-01 完成。',
        colors: [['#B7A98B', '卡其底'], ['#6B7353', '绿'], ['#7A5C3E', '棕'], ['#3E3F2C', 'AGSU 上衣'], ['#A9957F', '“pinks”']],
        why: 'OCP 经“最全面”的多地形、多季节、昼夜测试后选定，代价是十年内两次全军换迷彩；AGSU 官方明言是“重新启用‘最伟大的一代’所穿的制服”，给士兵一套尊重传统的职业装。',
        dispute: '“AGSU 2020 年开始配发”：官方页面只写 2020–21 年测试评估（中）；常被提及的“帮助征兵”动机未在官方原文中核到。',
        conf: '高', refs: ['us7', 'us8', 'us12', 'us16', 'us5'],
        fig: { headgear: { type: 'modern', cover: 'camo' }, coat: { cut: 'combat-shirt' }, camo: { type: 'multi', colors: ['#B7A98B', '#6B7353', '#7A5C3E', '#4a3a2a'], seed: 15 }, armor: 'vest', armorColor: '#6f6a52', belt: '#6f6a52', trousers: { style: 'bloused' }, footwear: '#7a6248' },
        fig2: { preset: 'us2020', title: 'AGSU 常服' },
        figNote: '示意图：只画“多地形”类型，不复刻 OCP / MultiCam 具体图案。依据：〔美7〕〔美12〕。',
        photos: ['us-2017-ocp-csm-portrait.jpg', 'us-2022-agsu-portrait-army.jpg', 'us-2018-oldguard-sentinel-dressblue.jpg'] }
    },

    ru: {
      E1: { name: '彼得一世的西欧式深绿 кафтан', year: 'c.1700 起；1780 年代波将金改革；1796–97 年保罗一世恢复普鲁士式',
        dress: '—（无区分）', service: '—', training: '—',
        combat: '深绿（“荨麻深绿”）кафтан + 红色饰面与宽翻袖口 + 背心 камзол + 黑三角帽，皮靴配绑腿。1783–86 年波将金推行短上衣、毡盔、短发、宽裤配包脚布；保罗一世即位后恢复普鲁士式长外衣、发辫与扑粉。',
        colors: [['#1F3A2B', '深绿'], ['#B22222', '红饰面']],
        why: '深绿成为近卫步兵“永远的象征”。此后俄军在“实用”与“阅兵美学”之间反复摇摆：波将金说衣服“是给士兵穿的，不是给他添累赘”；保罗一世崇拜腓特烈大帝，追求阅兵场上的整齐华丽。',
        dispute: '军服博物馆策展人把彼得一世的军服也说成“普鲁士式”，年代上不成立（普鲁士 1701 年才成王国），本页写“西欧式”；保罗一世改革年份有 1796 / 1797 两说；1812 年筒帽 кивер 的型制与年份未能核实，只以图版展示。',
        conf: '高（颜色、波将金改革）/ 中（保罗一世）', refs: ['ru14', 'ru18', 'ru19'],
        fig: { headgear: { type: 'tricorne', color: '#1d1b18' }, coat: { cut: 'justaucorps', color: '#1F3A2B' }, cuffs: '#B22222', turnbacks: '#B22222', waistcoat: '#1F3A2B', buttons: { color: '#c9a646' }, belt: '#5a3d24', trousers: { color: '#1F3A2B', style: 'breeches-gaiters' }, gaiters: '#1d1b18', weapon: 'musket' },
        figNote: '示意图：只画已核实的“深绿 + 红饰面 + 三角帽”，背心与马裤颜色从略（同上衣色）。依据：〔俄18〕〔俄19〕。',
        photos: ['ru-1700-preobrazhensky-bobrovsky.jpg', 'ru-1812-infantry-kiver-zaretsky.jpg'] },
      E2: { name: '亚历山大三世“民族风格”军服', year: '1881–1882',
        dress: '同一套“民族风格”军服：取消了头盔羽饰、艳色上衣、枪骑兵帽与骠骑兵外挂短衣。',
        service: '—（尚无现代意义的四分）', training: '—（夏季在突厥斯坦等地出现白色“体操衬衣”，年份待核）',
        combat: '宽松双排襟 кафтан 式上衣（肩章、立领）+ 带彩色嵌线的宽 шаровары 塞入高筒靴 + 带帽徽和国徽的羔皮帽。',
        colors: [['#1F3A2B', '深绿（沿用，待核）'], ['#1B1B1B', '羔皮帽（颜色待核）']],
        why: '国家历史博物馆称新军服“具有民族性质”，同时“更实用、更功利”；外观接近俄罗斯民间服装，贵族因此讥称亚历山大三世为“庄稼汉沙皇”。背景是 1881 年亚历山大二世遇刺后，新帝转向保守与民族主义。',
        dispute: '“节省经费”的动机没有找到来源，未采用；无外露纽扣（钩扣）的细节待核。',
        conf: '中–高', refs: ['ru13', 'ru14'],
        fig: { headgear: { type: 'papakha', color: '#1b1b1b', badge: '#c9a646' }, coat: { cut: 'frock', color: '#1F3A2B', length: 'thigh' }, buttons: { rows: 2, n: 0 }, collar: 'standing', shoulder: 'straps', shoulderColor: '#b33a2e', belt: '#5a3d24', trousers: { color: '#1F3A2B', style: 'boots', flare: true, stripe: '#b33a2e' }, footwear: '#1d1b18' },
        figNote: '示意图：羔皮帽、双排襟无扣上衣、灯笼裤塞靴；颜色与嵌线为示意。依据：国家历史博物馆〔俄13〕、军服博物馆〔俄14〕。',
        photos: [] },
      E3: { name: '保护色套头 гимнастёрка + фуражка', year: '日俄战争（1904–05）后；1916 年采用法制 Adrian 钢盔',
        dress: '1907–08 年恢复各团历史团名与团色，彩色礼服与保护色野战服从此分家（推断，待核）；1913 年炮兵以“保护色 китель + 彩色领”代替礼服上衣。',
        service: '保护色 гимнастёрка + 大檐帽 фуражка。', training: '同上。',
        combat: '保护色套头上衣束腰带 + 马裤 + 长靴；1916 年 4 月驻法俄国远征军先领用 Adrian 钢盔，同年夏全军采用，帽徽换成双头鹰。1917-12-16 人民委员会法令废除一切官阶、称号与“一切外部标志”。',
        colors: [['#8A845A', '保护色（灰绿卡其）']],
        why: '日俄战争的教训让保护色成为野战标准；法国钢盔是协约国之间最直接的装备外援。1917 年的法令要“尽快、坚决地消灭军队中旧不平等的一切残余”，肩章随之消失。',
        dispute: '保护色的具体年份（1907 / 1909 / 1910）与“1912 年式 гимнастёрка”未能核实；废除标志的日期：《祖国》杂志作 12-15，法令文本作 12-16，且法令没有点名“肩章”。',
        conf: '中（保护色年份）/ 高（Adrian、1917 法令）', refs: ['ru14', 'ru11', 'ru12', 'ru20', 'ru21', 'ru18'],
        fig: { headgear: { type: 'peaked', color: '#8A845A', band: '#8A845A', badge: '#c9a646' }, coat: { cut: 'blouse', color: '#8A845A' }, collar: 'standing', shoulder: 'straps', shoulderColor: '#8A845A', belt: '#5a3d24', beltBuckle: '#a4a494', trousers: { color: '#6f6b4c', style: 'boots', flare: true }, footwear: '#1d1b18' },
        figNote: '示意图：依据〔俄14〕与约 1910 年驻波斯俄军照片（黑白照片看不出颜色，卡其为按年代推断）。',
        photos: ['ru-1910-khaki-gimnastyorka-persia-bain.jpg'] },
      E4: { name: '1943 年立领 гимнастёрка + 肩章', year: '1943-01-06 最高苏维埃主席团令；01-15 国防人民委员 № 25 令，2 月 1–15 日换装',
        dress: '保留礼服上衣 мундир：立领高 4.5–4.8 厘米，元帅与将官领口、袖口金色橡叶刺绣。',
        service: 'гимнастёрка + 日常肩章（彩色底）。',
        training: '同一件 гимнастёрка（俄军至今没有独立的作训服类别）。',
        combat: 'гимнастёрка（翻领改为软立领，领口 2 扣、前襟 3 扣）+ 野战肩章（底色一律卡其）+ 船形帽或 SSh-40 钢盔。此前：1918–19 年布琼尼帽，1940 年改用护耳皮帽；1935 年恢复个人军衔。',
        colors: [['#7D7A55', '卡其 / 保护色'], ['#B8322A', '步兵红嵌线（日常肩章）']],
        why: '历史学者指出，肩章象征回到俄罗斯军事传统与民族国家，而不是“世界革命”；时机与斯大林格勒的胜利重合，用来强化纪律与指挥员威信，也面向盟国。同年 7 月恢复“军官”称谓。',
        dispute: 'SSh-40 的定型年份只有一处来源；布琼尼帽的命令号与日期只见百科。',
        conf: '高', refs: ['ru9', 'ru10', 'ru12', 'ru20', 'ru22'],
        fig: { preset: 'ru1943' },
        fig2: { title: '1919 年布琼尼帽', headgear: { type: 'budenovka', color: '#6f6f64', badge: 'star' }, coat: { cut: 'blouse', color: '#7D7A55' }, collar: 'standing', belt: '#5a3d24', trousers: { color: '#6f6b4c', style: 'boots', flare: true }, footwear: '#1d1b18' },
        figNote: '示意图：依据 1943 年 № 25 令原文〔俄9〕与 1926 年布琼尼帽照片。',
        photos: ['ru-1945-victory-parade-heroes-shoulder-boards-mosru.jpg', 'ru-1926-budenovka-gymnastyorka-bundesarchiv.jpg'] },
      E5: { name: '战后延续：立领套头衫 + 肩章', year: '1955-06-30 国防部第 105 号令（军官新制服）',
        dress: '1955 年军官礼服：“海浪色”（морская волна）上衣，配白衬衣与深灰领带（单一来源）。',
        service: '军官：卡其闭领上衣 + 蓝色长裤（1955，单一来源）。', training: '—',
        combat: '士兵沿用 1943 年体系的立领套头 гимнастёрка + 船形帽 / 钢盔，直到 1969 年后被废止（年份仅一处来源）。',
        colors: [['#7D7A55', '卡其'], ['#4F7F86', '海浪色（示意）']],
        why: '本期是资料最薄的一格：只找到一份描述 1955 年军官制服的军服百科，其余只能说明 1943 年的体系一直延续到 1960 年代末。',
        conf: '低', refs: ['ru25', 'ru15'],
        fig: { preset: 'ru1943', headgear: { type: 'ssh40', color: '#4d5236' } },
        figNote: '示意图：沿用 1943 年式样示意（置信度低）。',
        photos: [] },
      E6: { name: '“阿富汗卡”野战服', year: '1984-07 部长会议 № 722-158 决议 + 国防部 № 0145 令；1988-03-04 № 250 令最终确定',
        dress: '礼服与常服 1969 年改版的细节未能核实，不写。', service: '—（同上）', training: '同野战服 полевая。',
        combat: '“阿富汗卡”（афганка）：短夹克、翻领、胸袋与下摆袋都带袋盖、腰部抽绳、肘部加固；软檐帽有透气孔，可放下护颈护耳；夏装卡其或迷彩棉布，冬装絮棉夹克配人造毛领。',
        colors: [['#9A8F62', '阿富汗卡卡其']],
        why: '1969 年式长大衣与封闭式上衣在装甲车里施展不开；国防部中央被服局总结阿富汗作战经验，改成短夹克、多口袋，先配发驻阿部队，所以俗称“阿富汗卡”。此前 1969 年废止套头 гимнастёрка，据称也是为了伤员与核生化沾染时便于脱衣（低）。',
        conf: '中', refs: ['ru23', 'ru15'],
        fig: { preset: 'ru1985' }, figNote: '示意图：依据〔俄23〕与 1986 年苏军撤出阿富汗照片。',
        photos: ['ru-1986-afghanka-withdrawal-march-rian.jpg'] },
      E7: { name: '“Flora”迷彩 → 尤达什金军服与 ЕМР', year: '1994 年总统令 № 1010；VSR-98 1998；2008 年展示新军服、引入 ЕМР',
        dress: '1994-05-23 叶利钦总统令 № 1010，苏式军服正式退场；2008–2010 年时装设计师尤达什金（Валентин Юдашкин）设计的新礼服。',
        service: '尤达什金常服：橄榄色，胸前与袖上佩标志、魔术贴、收腰大衣；2011–12 年因吸湿差、-15 °C 以下保暖不足、做工差受到批评。',
        training: '同野战服。',
        combat: '1990 年代 VSR-93 → VSR-98“Flora”竖向条纹迷彩；2008 年起 ЕМР（“цифра”）数码迷彩取代 Flora。',
        colors: [['#5A5C3A', '橄榄常服'], ['#8F9A66', 'Flora 浅绿（示意）'], ['#4E5B3A', 'ЕМР 绿（示意）']],
        why: '谢尔久科夫时期的改革想用时装设计刷新军队形象，结果在保暖与做工上翻车，总投入约 250 亿卢布；2012 年绍伊古接任后承诺更换，尤达什金则称军方擅自改用廉价材料。',
        dispute: 'VSR-98 1998 年采用、ЕМР 2008 年引入：只找到一处军服百科写明年份（中）。',
        conf: '高（1994 令、尤达什金时间线）/ 中（迷彩年份）', refs: ['ru3', 'ru5', 'ru6', 'ru1', 'ru24'],
        fig: { headgear: { type: 'cap', cover: 'camo' }, coat: { cut: 'field' }, camo: { type: 'flora', colors: ['#8F9A66', '#556B3A', '#6E5A3A'], seed: 98 }, buttons: { color: '#3a3a2a' }, belt: '#4a4a36', trousers: { style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：只画“竖向条纹”类型。依据：〔俄24〕。',
        photos: [] },
      E8: { name: 'Ratnik 单兵系统 + ЕМР', year: '2015-05 首批交付；2017-08 正式列装；现行穿着规则为 2020-10-09 国防部 № 525 令',
        dress: 'парадная（队列 / 非队列两套）；总统团等仪仗队另有总统令 № 293 专设的“特殊礼仪礼服”。',
        service: 'повседневная（橄榄色）。',
        training: '规则明文：演习、训练课、战备值班穿 полевая——作训与作战是同一套。',
        combat: 'полевая + Ratnik（40 余个组件：武器、瞄具、防弹、通信、ГЛОНАСС 导航），6B47 头盔，ЕМР 数码迷彩。',
        colors: [['#4E5B3A', 'ЕМР 绿'], ['#6B5A3E', '褐'], ['#26261E', '黑'], ['#9AA07A', '浅绿']],
        why: '从“一套军服”变成“一套系统”：头盔、护甲、通信与导航和服装一起设计、一起配发。',
        dispute: 'Ratnik 的“2015 交付”与“2017 列装”是两件事；ВКПО 全季节野战服的年份本轮未能核实。',
        conf: '中–高', refs: ['ru1', 'ru2', 'ru7', 'ru8'],
        fig: { headgear: { type: 'modern', cover: 'camo', nvg: true }, coat: { cut: 'combat-shirt' }, camo: { type: 'digital', colors: ['#4E5B3A', '#6B5A3E', '#26261E', '#9AA07A'], seed: 8 }, armor: 'vest', belt: '#4a4a36', trousers: { style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：只画“数码像素”类型，不复刻 ЕМР 具体图案。依据：〔俄7〕〔俄8〕与 2018 年国防部照片。',
        photos: ['ru-2018-ratnik-emr-peace-mission-milru.jpg', 'ru-2014-presidential-regiment-parade-milru.jpg'] }
    },

    uk: {
      E1: { name: '红衣（redcoat）', year: '1645 新模范军；1742 年《Cloathing Book》；1751、1768 年皇家服装令',
        dress: '—（同一套红外套兼作阅兵与作战）', service: '—', training: '—（另有帆布 fatigue 罩衫与裤）',
        combat: '士兵茜草红长外套（1790 年代改为短尾 coatee），军官与士官为胭脂虫染的猩红；各团饰面色不同；白色交叉皮带；三角帽 → 1800 年起筒帽 shako；掷弹兵戴主教帽，后演变为熊皮帽。',
        colors: [['#A8322D', '士兵茜草红'], ['#C8102E', '军官猩红'], ['#1C2541', 'Royal 团深蓝饰面']],
        why: '成本（红色染料相对便宜）、耐晒、黑火药硝烟中便于识别，以及王室号衣色——四种解释并存。1751 与 1768 年皇家令禁止团长在装备上用私人纹章，用“饰面总表”把各团饰面色固定下来。',
        dispute: '各动机的排序没有定论；常见的“红色能掩盖血迹”在权威来源中找不到依据。',
        conf: '中', refs: ['uk1', 'uk5', 'uk18', 'uk26', 'uk28', 'uk30', 'uk32', 'uk33'],
        fig: { preset: 'uk1750' }, figNote: '示意图：取 1742 年第 20 步兵团的淡黄饰面。依据：1742 年《Cloathing Book》〔英30〕。',
        photos: ['uk-1742-20th-foot-cloathing-book.jpg', 'uk-1815-footguards-knotel.jpg'] },
      E2: { name: '猩红 tunic + 本土勤务盔；殖民地卡其', year: '1855 年 tunic 取代 coatee；1878 年 Home Service Helmet；1848 年导向团首创卡其',
        dress: '猩红 tunic + 筒帽（1855–78），1878 年起换深蓝布面尖顶盔；近卫步兵戴熊皮帽。',
        service: '约 1870 年起出现朴素的“Frock”工作上衣，颜色同全礼服。',
        training: '军官 stable jacket / shell jacket；士兵 fatigue 服。',
        combat: '在欧洲仍穿红衣（克里米亚战争）；殖民地战场穿卡其布（khaki drill）+ 外勤遮阳盔。',
        colors: [['#C8102E', '猩红 tunic'], ['#1F2533', '深蓝长裤'], ['#1F2A44', '本土勤务盔'], ['#C3B091', '卡其布']],
        why: '1878 年的本土勤务盔“像普鲁士式那样带尖顶——正是普鲁士式促成了它的采用”（Barthorp）；而在印度西北边境，Harry Lumsden 意识到传统军服“无论活动还是隐蔽都不实用”，1848 年用尘土色布做出第一批卡其。',
        dispute: '士兵深红改猩红的年份：条例作约 1870，Barnes 作 1873；卡其推广的中间节点（1857、1868、1880 年代）只有单一来源。',
        conf: '高（1855、1878、1848）', refs: ['uk1', 'uk2', 'uk5', 'uk17', 'uk18', 'uk19', 'uk20'],
        fig: { headgear: { type: 'hsh', color: '#1F2A44' }, coat: { cut: 'tunic', color: '#C8102E' }, collarColor: '#1C2541', cuffs: '#1C2541', buttons: { n: 7, color: '#c9a646' }, shoulder: 'straps', shoulderColor: '#C8102E', belt: '#f2efe6', beltBuckle: '#c9a646', trousers: { color: '#1F2533', stripe: '#C8102E' }, footwear: '#1d1b18', weapon: 'rifle' },
        figNote: '示意图：领、袖饰面取 Royal 团深蓝；依据：〔英1〕〔英17〕与 1881 年第 40 团掌旗军士图版（该图戴的是海外用白色外勤盔）。',
        photos: ['uk-1881-scarlet-tunic-colour-sergeant.jpg'] },
      E3: { name: '1902 式卡其 Service Dress + Brodie 钢盔', year: '1902 年；Brodie 1915 年设计、1916 年定名 Mark I',
        dress: '猩红全礼服保留到 1914 年；战后除近卫师、乐队等外没有恢复（经费考虑）。',
        service: 'Service Dress（卡其哔叽）；军官款 1913 年改为开领、露出衬衫与领带。',
        training: '衬衫袖装、fatigue 服。',
        combat: 'SD（士兵为立领、单排 5 扣、两个胸袋）+ 绑腿 + 1908 式织带装具 + Brodie 钢盔。',
        colors: [['#7C6A46', 'SD 卡其'], ['#6B6A45', 'Brodie 卡其绿']],
        why: '第二次布尔战争的教训让卡其从殖民地走向全军。Brodie 的结论是“相对简单的头盔就能提供合理防护，耐用且便宜”：一次冲压成型，宽帽檐防护头顶上方落下的弹片——代价是颈部防护不足。',
        conf: '高', refs: ['uk1', 'uk3', 'uk8', 'uk9', 'uk18', 'uk25'],
        fig: { preset: 'uk1916' }, figNote: '示意图：依据〔英3〕〔英8〕与 1916 年索姆河照片。',
        photos: ['uk-1916-somme-brodie-helmet-iwm.jpg', 'uk-1917-service-dress-full-kit-iwm.jpg', 'uk-1900-boer-war-khaki-iwm.jpg'] },
      E4: { name: '1937 式 Battledress', year: '1937 年型号；1939 年起大范围配发；1942 年 Denison 伞兵迷彩罩衫',
        dress: '全礼服只剩近卫与乐队；1937 年加冕礼发给士兵蓝色哔叽制服，是 No.1 Dress 的前身。',
        service: '军官保留 SD；士兵以 Battledress 兼作外出服。',
        training: '牛仔布工作服（Denim Overalls，款式同 BD）。',
        combat: 'BD（齐腰短夹克 + 高腰裤，短绑腿）+ Brodie 式钢盔；伞兵与特种部队穿 Denison 笔刷迷彩罩衫；1924 年起坦克兵戴贝雷帽，二战中普及。',
        colors: [['#6E6445', 'BD 卡其哔叽'], ['#C9B78E', 'Denison 沙底'], ['#7A8450', '豆绿笔触'], ['#5A3D2B', '深棕笔触']],
        why: '国家陆军博物馆称它是“标准的工作服兼作战服……舒适实用”；“按机械化步兵需要设计、参考羊毛滑雪服、省料”的说法只见一处来源（中）。1940 年简化型再省去暗门襟与口袋褶，以节省工时。',
        conf: '中', refs: ['uk1', 'uk4', 'uk5', 'uk21', 'uk23', 'uk28'],
        fig: { preset: 'uk1944' },
        fig2: { title: 'Denison 罩衫（示意）', headgear: { type: 'beret', color: '#3a3430' }, coat: { cut: 'field' }, camo: { type: 'brush', colors: ['#C9B78E', '#7A8450', '#5A3D2B'], seed: 42 }, buttons: { color: '#3a3a2a' }, belt: '#8a7f5a', trousers: { color: '#6E6445', style: 'anklets', camo: false }, gaiters: '#8a7f5a', footwear: '#1d1b18' },
        figNote: '示意图：Denison 只画“笔刷”类型，贝雷帽颜色从略。依据：〔英4〕〔英5〕〔英21〕〔英23〕。',
        photos: ['uk-1940-battledress-bef-iwm.jpg', 'uk-1942-battledress-paratrooper-colour-iwm.jpg'] },
      E5: { name: '1960 式橄榄绿作战服；No.1 / No.2 Dress 成形', year: 'BD 用到 1950 年代末；No.1 到 1950 年成形；约 1960 年士兵 SD 改开领',
        dress: 'No.1 Dress：深蓝 tunic + 大檐帽（团队色帽带）；全礼服仍只限近卫与乐队。',
        service: 'Battledress → 约 1960 年起 No.2 Dress（卡其开领，衬衫打领带）。',
        training: '牛仔布工作服、衬衫加毛衣的营房服。',
        combat: '1960 式橄榄绿作战服（宽松罩衫 + 裤 + 兜帽）+ 钢盔；空降兵仍穿 Denison。',
        colors: [['#5B5B3A', '1960 式橄榄绿'], ['#1C2541', 'No.1 深蓝'], ['#7C6A46', 'No.2 卡其']],
        why: '作战服与常服彻底分家：卡其留给阅兵式的 No.2，野外改穿更宽松、能叠穿的单色橄榄绿罩衫。',
        dispute: '1949 式 Battledress 的开领细节只见一处来源。',
        conf: '中', refs: ['uk1', 'uk4', 'uk10', 'uk21', 'uk22', 'uk35'],
        fig: { headgear: { type: 'beret', color: '#2a2e38' }, coat: { cut: 'field', color: '#5B5B3A' }, buttons: { color: '#3a3a2a' }, belt: '#7a7458', trousers: { color: '#5B5B3A', style: 'anklets' }, gaiters: '#7a7458', footwear: '#1d1b18' },
        fig2: { title: 'No.2 Dress（卡其开领）', headgear: { type: 'peaked', color: '#7C6A46', band: '#7C6A46', badge: '#c9a646' }, coat: { cut: 'service', color: '#7C6A46' }, collar: 'open-tie', shirt: '#c8b48f', tie: '#6b5a3c', buttons: { n: 4, color: '#c9a646' }, trousers: { color: '#7C6A46' }, footwear: '#1d1b18' },
        figNote: '示意图：贝雷帽颜色因团而异，此处取深色示意。依据：〔英1〕〔英22〕。',
        photos: [] },
      E6: { name: 'DPM 迷彩（1968 式作战服）', year: '1968 年定型生产、1969 年开始配发、1970 年代普及',
        dress: 'No.1 Dress / 全礼服（近卫）。', service: 'No.2 Dress。',
        training: 'No.13 营房服（衬衫、毛衣、裤子与帽子的组合）。',
        combat: 'No.8 温带作战服：DPM 罩衫（四个带盖口袋、兜帽可扣于领后）+ 同色裤，贝雷帽或钢盔；1980 年代末少量沙漠 DPM。',
        colors: [['#B9A77A', '深沙底'], ['#5E6B3A', '中绿'], ['#5A3E2B', '深棕'], ['#1E1E1E', '黑']],
        why: '英国第一种普遍配发的迷彩作战服，为欧洲温带林地设计；此后四十年没有换过迷彩。',
        dispute: '“1963 年先给特种部队、1966 年部分装备”只见百科；帝国战争博物馆称 1968 年生产、1969 年配发。',
        conf: '中', refs: ['uk6', 'uk10', 'uk11', 'uk22', 'uk28'],
        fig: { preset: 'uk1990' }, figNote: '示意图：只画“笔刷斑块”类型，不复刻 DPM 具体图案。依据：〔英10〕〔英22〕。',
        photos: ['uk-1980-dpm-reforger-slr-dod.jpg', 'uk-1993-dpm-l85a1-roaring-lion-dod.jpg'] },
      E7: { name: '沙漠 DPM → CS95 → MTP', year: '1990–91 海湾战争；1995 年 CS95；2009-12 公布 MTP，2010 年 3–4 月起配发',
        dress: 'No.1。', service: 'No.2。', training: 'No.13 / No.14。',
        combat: 'CS95 分层服装系统（林地或沙漠 DPM）→ 2010 年起向赴阿富汗部队配发 MTP 多地形迷彩。',
        colors: [['#E0CDA6', '沙漠 DPM 沙底'], ['#B89B72', '浅棕']],
        why: '赫尔曼德河沿岸是狭长的灌溉“绿区”，两侧是荒漠，士兵一天多次进出，只好混穿林地与沙漠两种 DPM；国防部用航拍取色、计算机模拟，6 个月、约 25 万英镑研制出 MTP。',
        conf: '高（MTP）/ 中（CS95、沙漠 DPM）', refs: ['uk11', 'uk12', 'uk13', 'uk22', 'uk31'],
        fig: { headgear: { type: 'pasgt', cover: 'camo' }, coat: { cut: 'field' }, camo: { type: 'brush', colors: ['#E0CDA6', '#B89B72', '#C9B48C'], seed: 91 }, buttons: { color: '#6b5a3c' }, belt: '#8a7f5a', trousers: { style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：1991 年两色沙漠 DPM，只画类型。依据：〔英22〕〔英31〕。',
        photos: [] },
      E8: { name: 'PCS-CU（MTP）+ Virtus', year: 'PCS 2011-02 宣布、2013-04 前基本换装；Virtus 2015-07 发布、2016 年起配发',
        dress: '全礼服（近卫师等公费穿着）+ No.1 Dress。',
        service: 'No.2 Dress（“自 2009 年起统一为标准配发款”，条例称 Future Army Dress）。',
        training: 'No.13 / No.14；PCS-CU 也可在营区日常穿着。',
        combat: 'No.8 = PCS-CU（MTP 迷彩，非迷彩件为卡其色）+ Virtus 头盔与护甲：比 Osprey 轻约 4.7–5 公斤，护板可按威胁增减，背部有负重脊架。',
        colors: [['#C2B28F', '沙底'], ['#7E7A52', '橄榄'], ['#5B4A36', '棕'], ['#3E4531', '深绿']],
        why: 'MTP 以 Crye Precision 的 MultiCam 为基础、换上 DPM 的斑块形状，“在最广泛的环境中表现最好”，只在纯林地或纯荒漠中略逊于专用款；它受管控、不许商业销售。',
        conf: '高', refs: ['uk1', 'uk11', 'uk12', 'uk13', 'uk14', 'uk15', 'uk16', 'uk24'],
        fig: { preset: 'uk2012' }, figNote: '示意图：只画“多地形”类型，不复刻 MTP / MultiCam 具体图案。依据：〔英13〕〔英14〕。',
        photos: ['uk-2014-mtp-sandhurst-grafenwoehr-dod.jpg', 'uk-2014-foot-guards-windsor-delso.jpg'] }
    },

    fr: {
      E1: { name: '旧制度白衣 → 帝国蓝 habit-veste', year: '1779-02-21 服装条例；大革命后改蓝；1806-02-25 筒帽；1812 年 Bardin 条例',
        dress: '—（同一套 habit 兼作；1806 年起配灰 / 米色大衣防雨寒）', service: '—', training: '—',
        combat: '1812：深蓝 habit-veste（宽松、短燕尾、白翻领扣到腰）、红领红袖口、白马甲白马裤、黑长绑腿、白交叉背带、带鹰徽铜牌的黑筒帽。旧制度步兵为白 / 灰白上衣与三角帽。',
        colors: [['#E6E1D3', '旧制度灰白'], ['#1F2A4D', '国民蓝'], ['#F2F0E6', '白翻领'], ['#B22222', '红领袖']],
        why: '帝国时期“蓝为国民色”——大革命把国王军队的白换成了国民的蓝；学界也把蓝衣看作政治符号与染料供应约束共同作用的结果。',
        dispute: '路易十四时期灰白的起点年份、1806 年短暂恢复白衣：未能核实，不写；1812 年各团饰面配色只作示意。',
        conf: '高（1779、1806）/ 中（1812）', refs: ['fr4', 'fr5', 'fr6', 'fr11', 'fr15'],
        fig: { preset: 'fr1812' }, figNote: '示意图：依据 Houdecek〔法4〕与 Carle Vernet 1812 年图版。',
        photos: ['fr-1812-line-infantry-carle-vernet.jpg', 'fr-1776-gatinois-infantry-juillet.jpg', 'fr-1786-neustrie-grenadier-captain-musee-armee.jpg'] },
      E2: { name: '茜草红裤 + 深蓝大衣 + képi', year: '1829 年采用红裤；一直穿到 1914 年 8 月',
        dress: '圣西尔 1845 年设大礼服（GU），1855 年为维多利亚女王检阅首次戴红白下垂羽饰 casoar。',
        service: '—（未核）', training: '—（未核）',
        combat: '深蓝 / 灰蓝双排扣长大衣（前襟下摆常向后扣起）+ 茜草红长裤 + 红顶 képi + 短绑腿。',
        colors: [['#B0282E', '茜草红'], ['#3C4A68', '大衣深蓝灰']],
        why: '常见解释是扶持本国茜草种植与染色业；讽刺在于 1869 年前后合成茜素问世后法国茜草业衰落，到 1914 年红色染料反而依赖德国。',
        dispute: '动机只有一处明言；1984 年《陆军历史评论》的专文未能读到全文。',
        conf: '高（年份）/ 中（动机）', refs: ['fr1', 'fr2', 'fr8', 'fr10', 'fr15', 'fr16'],
        fig: { preset: 'fr1914' }, figNote: '示意图：依据〔法1〕与莫城一战博物馆的 1914 年复原展品。',
        photos: ['fr-1914-pantalon-rouge-musee-meaux.jpg', 'fr-1914-infantry-kepi-greatcoat-bain-loc.jpg'] },
      E3: { name: '地平线蓝 + Adrian 钢盔', year: '1914-12-09 通知采用 bleu horizon；1915 年 Adrian 钢盔；1916 年秋才普及',
        dress: '战时停用。', service: '—（与作战服合一）', training: '—',
        combat: '地平线蓝大衣与长裤 + 绑腿 + Adrian 钢盔（顶脊、前后帽檐）；非洲与殖民部队穿芥末黄卡其（kaki moutarde）。战前试验：1902–06 年“布尔色”与“米灰蓝”，1911 年 2,500 人试穿木犀草绿 réséda，均被否决；1914 年 7 月才立法换色。',
        colors: [['#7B96B2', '地平线蓝'], ['#A8904F', '芥末卡其']],
        why: '1914 年 8 月 22 日一天至少 2.5 万法军阵亡，红裤是因素之一；德国产合成茜素断供，也让红色难以为继。地平线蓝由深蓝、浅蓝、白线混纺而成。',
        conf: '高', refs: ['fr1', 'fr2', 'fr3', 'fr8', 'fr12', 'fr14'],
        fig: { preset: 'fr1916' }, figNote: '示意图：依据军事博物馆〔法1〕与 1917 年天然色干版照片。',
        photos: ['fr-1917-horizon-blue-adrian-autochrome.jpg'] },
      E4: { name: '卡其大衣 + Adrian 钢盔', year: '1935 年全军以卡其取代地平线蓝；1936-05-09 从条例文本删除 bleu horizon',
        dress: '圣西尔 1933 年 10 月恢复传统 GU（黑 / 深蓝上衣、天蓝领袖、茜草红裤配蓝侧条）；外籍军团白 képi 1939-07-14 首次在巴黎受阅。',
        service: '—（未核）', training: '—（未核）',
        combat: '卡其（芥末黄褐）双排扣长大衣 + 绑腿 + Adrian 钢盔（1940 年）。',
        colors: [['#7A6A44', '卡其（估计）']],
        why: '法国是五国里最后一个放弃蓝色系野战服的：从 1915 年的地平线蓝到 1935 年的卡其，才与英、美、苏的土色阵营合流。',
        dispute: '自由法军 1940–45 年先穿英制、1943 年后换美制——本轮没有找到两份可引来源。',
        conf: '中', refs: ['fr13', 'fr14', 'fr15'],
        fig: { headgear: { type: 'adrian', color: '#5d5b41' }, coat: { cut: 'frock', color: '#8a7a4c' }, buttons: { rows: 2, n: 6, color: '#6b6242' }, collar: 'turndown', belt: '#5a3a24', pouches: '#5a3a24', trousers: { color: '#8a7a4c', style: 'puttees' }, puttees: '#8a7a4c', footwear: '#3a2a1e', weapon: 'rifle' },
        figNote: '示意图：依据〔法14〕与 1940 年 5 月第 124 步兵团军服原件展陈。',
        photos: ['fr-1940-khaki-capote-adrian-124ri.jpg'] },
      E5: { name: '“蜥蜴纹”（lizard）伞兵迷彩', year: '1947 年起：M1947/51 为首款量产罩衫（印度支那），M1947/56 为最终改型',
        dress: '圣西尔 GU 1946 年一度取消，1947 年 7 月 14 日羽饰与白手套重现，1949 年全面恢复；外籍军团 1952 年正式记载白帽罩的配发。',
        service: '—（未核）', training: '—（未核）',
        combat: '空降部队与外籍军团空降部队穿 lizard 罩衫：单排扣、宽松、四个风箱口袋；浅绿底上横向刷痕状的深绿与红棕条纹；贝雷帽。一般部队的服色本轮未核。',
        colors: [['#9AA67A', '浅绿底'], ['#3E4A2C', '深绿'], ['#6B3F2A', '红棕']],
        why: '从印度支那到阿尔及利亚，迷彩成了伞兵精英的身份标志——也正因此卷入政治。',
        dispute: '“伞兵迷彩 1963 年 1 月撤装，原因是让人联想到 1961 年伞兵参与的将军叛乱”：只有百科转引一部 Osprey（低），实务原因说未找到来源；1979 年吉布提仍有部队穿 lizard，说明撤装并不彻底。“受英国 Denison 罩衫启发”只见百科（低）。',
        conf: '中（外观与年代）/ 低（撤装原因）', refs: ['fr10b', 'fr17', 'fr13', 'fr15', 'fr24'],
        fig: { preset: 'fr1956', headgear: { type: 'beret', color: '#2b2b2b' } },
        figNote: '示意图：只画“横向刷痕”类型；贝雷帽颜色因部队而异，此处取深色。依据：帝国战争博物馆藏品说明〔法17〕。',
        photos: ['fr-1979-lizard-camouflage-6e-rama-djibouti.jpg'] },
      E6: { name: '素色作战服（Satin 300 / F1）', year: '1964 年 Satin 300；F1 1978 年（另说 1980 年代初）',
        dress: 'grande tenue / tenue de tradition（各团传统礼服）。', service: 'tenue de sortie（外出服，通行叫法）。',
        training: '日常训练穿作战服 treillis。',
        combat: '“Satin 300”（300 g/m² 棉缎，陆军绿）→ F1 涤棉人字纹作战服；素色，无迷彩。',
        colors: [['#4B5A3A', '橄榄绿（估计）']],
        why: '撤下伞兵迷彩之后，法军回到素色橄榄绿，直到 1990 年代才全军换回迷彩——五国中迷彩化最晚。',
        dispute: '官方社媒把它叫作“Satin 300 modèle F1”，两个名称有重叠；“F1 1978 / F2 1984”（收藏者文章）与“F1 1980 年代初 / F2 1990 年代”说法不一。',
        conf: '低–中', refs: ['fr18', 'fr19'],
        fig: { headgear: { type: 'beret', color: '#2b2b2b' }, coat: { cut: 'field', color: '#4B5A3A' }, buttons: { color: '#3a3a2a' }, belt: '#3a3a2a', trousers: { color: '#4B5A3A', style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：素色作战服，贝雷帽颜色从略。依据：〔法18〕。',
        photos: [] },
      E7: { name: 'CCE 中欧迷彩（F2 作战服）', year: '1990 年代引入（一说 1991，一说 1994 年随改版 F2）；Daguet 沙漠迷彩 1990–93',
        dress: 'grande tenue / tenue de tradition。', service: 'tenue de service courant（日常勤务服）。',
        training: '作战服 treillis。',
        combat: 'F2 作战服 + CE 四色林地迷彩（绿、棕、黑、卡其）；2010 年起交付 FÉLIN 单兵系统（头盔、战术背心、单兵电台、光电瞄具）。',
        colors: [['#8A8456', '卡其'], ['#4E5B35', '绿'], ['#5A4632', '棕'], ['#1E1E1A', '黑']],
        why: '冷战结束前后，法军终于采用全军迷彩：林地与沙漠两套，此后沿用约 30 年。',
        dispute: 'CE 定型年份：1991（常见说法）/ 1994（收藏者文章）/“1990 年代”（官方）。',
        conf: '中', refs: ['fr18', 'fr20', 'fr21'],
        fig: { headgear: { type: 'beret', color: '#2b2b2b' }, coat: { cut: 'field' }, camo: { type: 'woodland', colors: ['#8A8456', '#4E5B35', '#5A4632', '#1E1E1A'], seed: 94 }, buttons: { color: '#3a3a2a' }, belt: '#3a3a2a', trousers: { style: 'bloused' }, footwear: '#1d1b18' },
        figNote: '示意图：只画“林地斑块”类型。依据：〔法18〕〔法20〕。',
        photos: ['fr-1996-cce-camouflage-40e-ra-dod.jpg'] },
      E8: { name: 'BME 多环境迷彩', year: '2016-03 开始设计；2022-05-12 公布；2024-12 起首批配发',
        dress: 'grande tenue：圣西尔 GU（筒帽 + casoar 羽饰、深蓝上衣、红裤蓝侧条）、外籍军团白 képi 等传统礼服。',
        service: '条例第 2 类：tenue de cérémonie / tenue de service courant。',
        training: '作战服（条例未单列作训服）。',
        combat: 'BME：长裤、作战衬衫与配防弹背心穿的战术衬衫；6 色，取代 CE 与沙漠迷彩（另保留雪地型）；官方称“被发现的延迟”提高 25%。',
        colors: [['#B9A983', '沙'], ['#7C7A55', '橄榄'], ['#6E5A42', '褐'], ['#3B3A2E', '深褐']],
        why: '后勤上两套迷彩变一套、多战区通用，并在 30 年后更新视觉形象；由陆军技术处 STAT 设计、法国企业量产，投资约 2 亿欧元。',
        conf: '高', refs: ['fr20', 'fr22', 'fr23'],
        fig: { headgear: { type: 'modern', cover: 'camo' }, coat: { cut: 'combat-shirt' }, camo: { type: 'multi', colors: ['#B9A983', '#7C7A55', '#6E5A42', '#3B3A2E'], seed: 22 }, armor: 'vest', armorColor: '#5f5d45', belt: '#5f5d45', trousers: { style: 'bloused' }, footwear: '#6a5a44' },
        figNote: '示意图：只画“多环境斑块”类型，颜色为示意，不复刻 BME 具体图案。依据：〔法20〕〔法23〕。',
        photos: ['fr-2013-saint-cyr-grand-uniforme-nguyen.jpg', 'fr-2013-foreign-legion-kepi-blanc-nguyen.jpg'] }
    }
  };

  /* ---------- 颜色演变总线：每国野战 / 作战服的主色 ---------- */
  var BUS = {
    stages: [
      { a: 1700, b: 1900, name: '鲜艳', note: '敌我识别、招募与威慑、国家象征' },
      { a: 1900, b: 1946, name: '卡其 / 灰', note: '无烟火药与远射程步枪让显眼成了负担' },
      { a: 1946, b: 1995, name: '迷彩', note: '先是精锐与特种部队，再到全军' },
      { a: 1995, b: 2010, name: '数码', note: '像素化的小色块' },
      { a: 2010, b: 2026, name: '多地形', note: '一套图案通吃多种地形，与护甲一体' }
    ],
    lanes: {
      cn: [
        { a: 1700, b: 1905, t: 'hatch', c: ['#2B3B5C', '#B33A2E', '#E8B800'], label: '甲胄与号衣：醒目，色因营而异' },
        { a: 1905, b: 1929, t: 'split', c: ['#2B3A55', '#B8995A'], label: '新军：冬深蓝 / 夏土黄' },
        { a: 1929, b: 1936, t: 'solid', c: ['#6E7275'], label: '国军与红军：灰' },
        { a: 1936, b: 1949, t: 'solid', c: ['#9C8F5E'], label: '草黄（1936 条例）' },
        { a: 1949, b: 1965, t: 'solid', c: ['#6B6A3F'], label: '草绿 / 棕绿（50、55 式）' },
        { a: 1965, b: 1988, t: 'solid', c: ['#707A45'], label: '65 式草绿' },
        { a: 1988, b: 2007, t: 'woodland', c: ['#8b8a5c', '#4d5b33', '#5b4632', '#2a2a22'], label: '87 式林地迷彩' },
        { a: 2007, b: 2021, t: 'digital', c: ['#4f6b3a', '#2e3b26', '#6b5a3e', '#1f1f1a'], label: '07 式数码（按军种）' },
        { a: 2021, b: 2026, t: 'digital', c: ['#5E6B45', '#6E5A3E', '#23261E', '#A8A27A'], label: '21 式（按地形）', fine: true }
      ],
      us: [
        { a: 1775, b: 1898, t: 'solid', c: ['#1F2F4F'], label: '大陆军蓝 → 联邦蓝' },
        { a: 1898, b: 1902, t: 'solid', c: ['#C3B091'], label: '卡其' },
        { a: 1902, b: 1946, t: 'solid', c: ['#5F5B3C'], label: '橄榄褐 OD' },
        { a: 1946, b: 1981, t: 'solid', c: ['#5C5F3B'], label: 'OG 橄榄绿' },
        { a: 1981, b: 2005, t: 'woodland', c: ['#8A9A5B', '#6B4E31', '#3B4A2C', '#1C1C1C'], label: 'M81 林地' },
        { a: 2005, b: 2015, t: 'digital', c: ['#C2B8A3', '#8A8D8F', '#6E7B63'], label: 'UCP 通用数码' },
        { a: 2015, b: 2026, t: 'multi', c: ['#B7A98B', '#6B7353', '#7A5C3E'], label: 'OCP 多地形' }
      ],
      ru: [
        { a: 1700, b: 1907, t: 'solid', c: ['#1F3A2B'], label: '深绿' },
        { a: 1907, b: 1984, t: 'solid', c: ['#7D7A55'], label: '保护色 / 卡其' },
        { a: 1984, b: 1993, t: 'solid', c: ['#9A8F62'], label: '阿富汗卡' },
        { a: 1993, b: 2008, t: 'flora', c: ['#8F9A66', '#556B3A', '#6E5A3A'], label: 'Flora 竖纹' },
        { a: 2008, b: 2026, t: 'digital', c: ['#4E5B3A', '#6B5A3E', '#26261E', '#9AA07A'], label: 'ЕМР 数码' }
      ],
      uk: [
        { a: 1700, b: 1902, t: 'solid', c: ['#A8322D'], label: '红衣' },
        { a: 1902, b: 1960, t: 'solid', c: ['#7C6A46'], label: '卡其（SD → BD）' },
        { a: 1960, b: 1968, t: 'solid', c: ['#5B5B3A'], label: '1960 式橄榄绿' },
        { a: 1968, b: 2010, t: 'brush', c: ['#B9A77A', '#5E6B3A', '#5A3E2B', '#1E1E1E'], label: 'DPM' },
        { a: 2010, b: 2026, t: 'multi', c: ['#C2B28F', '#7E7A52', '#5B4A36'], label: 'MTP' },
        { a: 1848, b: 1902, t: 'solid', c: ['#C3B091'], label: '殖民地卡其', minor: true },
        { a: 1942, b: 1968, t: 'brush', c: ['#C9B78E', '#7A8450', '#5A3D2B'], label: 'Denison（伞兵）', minor: true }
      ],
      fr: [
        { a: 1700, b: 1793, t: 'solid', c: ['#E6E1D3'], label: '旧制度白 / 灰白' },
        { a: 1793, b: 1829, t: 'solid', c: ['#1F2A4D'], label: '国民蓝' },
        { a: 1829, b: 1915, t: 'split', c: ['#3C4A68', '#B0282E'], label: '蓝大衣 + 红裤' },
        { a: 1915, b: 1935, t: 'solid', c: ['#7B96B2'], label: '地平线蓝' },
        { a: 1935, b: 1947, t: 'solid', c: ['#7A6A44'], label: '卡其' },
        { a: 1947, b: 1964, t: 'unknown', c: ['#9a9a90'], label: '一般部队服色待核' },
        { a: 1964, b: 1991, t: 'solid', c: ['#4B5A3A'], label: '素色橄榄（Satin 300 / F1）' },
        { a: 1991, b: 2024, t: 'woodland', c: ['#8A8456', '#4E5B35', '#5A4632', '#1E1E1A'], label: 'CCE' },
        { a: 2024, b: 2026, t: 'multi', c: ['#B9A983', '#7C7A55', '#6E5A42'], label: 'BME' },
        { a: 1947, b: 1963, t: 'lizard', c: ['#9AA67A', '#3E4A2C', '#6B3F2A'], label: 'lizard（伞兵）', minor: true }
      ]
    }
  };

  /* ---------- 转折点卡片（设计原因）---------- */
  var CARDS = [
    { id: 'uk-redcoat', cc: 'uk', era: 'E1', year: '1645–1768', title: '红衣成为“英国色”', tags: ['politics', 'tech', 'combat'],
      what: '1645 年议会的新模范军步兵统一穿红外套，各团只以饰面色区分；1742 年《Cloathing Book》以图版记录各团服装，1751 与 1768 年皇家令把饰面色固定下来。',
      why: '四种解释并存：红色染料相对便宜；红色耐晒不易褪；黑火药战场烟雾弥漫，“军队其实希望士兵显眼”（国家陆军博物馆）；Royal 团的深蓝饰面与王室号衣色挂钩。',
      dispute: '动机排序没有定论；“红色能掩盖血迹”一说找不到权威依据。', conf: '中', refs: ['uk5', 'uk18', 'uk26', 'uk27', 'uk32', 'uk33'] },
    { id: 'us-blue', cc: 'us', era: 'E1', year: '1779', title: '大陆军统一穿蓝', tags: ['politics', 'combat'],
      what: '1779-10-02 华盛顿总命令规定全军蓝上衣，按州分区用白、浅黄、红、蓝四种饰面色，炮兵猩红饰面。',
      why: '要与英军“红衫”区分；1775 年定的棕色因缺布名存实亡，1778 年法国援助的成衣本就是蓝、棕两色，条令顺着供货走；华盛顿本人自 1775 年就穿“蓝 + 浅黄”。蓝色从此成为美国陆军的“祖色”，2010 年蓝色礼服回归即以此为据。',
      dispute: '步兵统一红饰面：1782（NARA）与 1779（陆军军史中心摘录）。', conf: '高（条令）/ 中（动机）', refs: ['us1', 'us2', 'us3', 'us4'] },
    { id: 'ru-potemkin', cc: 'ru', era: 'E1', year: '1783–1797', title: '波将金的实用军服 vs 保罗一世的普鲁士式', tags: ['combat', 'culture', 'politics'],
      what: '波将金 1783 年上书叶卡捷琳娜二世，随后推行短上衣、毡盔、短发、宽裤配包脚布；保罗一世即位后全部推翻，恢复普鲁士式长外衣、发辫与扑粉。',
      why: '波将金：“衣服是给士兵穿的，不是给他添累赘”——舒适、卫生（发辫易生虱）、省钱；保罗一世崇拜腓特烈大帝，追求阅兵场上的整齐华丽。这是俄国军服史上“实用 vs 阅兵美学”第一次正面冲突。',
      dispute: '保罗改革年份：1796 年即位后 / 1797 年。', conf: '中–高', refs: ['ru14', 'ru19'] },
    { id: 'uk-bearskin', cc: 'uk', era: 'E1', year: '1815', title: '熊皮帽：从滑铁卢缴来的荣誉', tags: ['culture', 'politics'],
      what: '滑铁卢战役后，第一近卫步兵团为纪念击败法兰西帝国近卫军掷弹兵，采用对方的熊皮帽与燃烧手榴弹帽徽，并获“掷弹兵”称号；此后推广到全部近卫步兵。',
      why: '以敌方精锐的标志性头饰纪念胜利，把“掷弹兵”的历史身份变成荣誉符号——直到今天，白金汉宫前的卫兵仍戴着它。',
      dispute: '常说“1815 年改名 Grenadier Guards”，实际正式定名要到 1877 年；1751、1768 年的皇家令已给掷弹兵（军官）配熊皮帽，1815 年的变化是整团都戴。', conf: '高', refs: ['uk1', 'uk7', 'uk32', 'uk33'] },
    { id: 'fr-garance', cc: 'fr', era: 'E2', year: '1829', title: '茜草红裤：“国货”与国家形象', tags: ['politics', 'culture', 'tech'],
      what: '1829 年法军步兵改穿茜草染的红裤，与深蓝大衣、红顶 képi 构成一直延续到 1914 年的“红裤兵”形象。',
      why: '常见解释是扶持本国茜草种植与染色业。讽刺在于 1869 年前后合成茜素问世，法国茜草业随之衰落；到 1914 年，红色染料反而依赖德国，一开战就断了供。',
      dispute: '动机只有一处明言；1984 年《陆军历史评论》专文未能读取。', conf: '高（年份）/ 中（动机）', refs: ['fr1', 'fr7', 'fr8', 'fr10'] },
    { id: 'ru-1881', cc: 'ru', era: 'E2', year: '1881–82', title: '亚历山大三世的“民族风格”', tags: ['culture', 'politics'],
      what: '陆军换装宽松双排襟 кафтан 式上衣、带嵌线的宽灯笼裤与羔皮帽，取代头盔羽饰、艳色上衣、枪骑兵帽与骠骑兵外挂短衣。',
      why: '国家历史博物馆说新军服“具有民族性质”，同时“更实用、更功利”；外观接近民间服装，贵族讥称沙皇为“庄稼汉沙皇”。背景是 1881 年亚历山大二世遇刺后新帝转向保守与俄罗斯民族主义。',
      dispute: '“节省经费”的动机没有找到来源。', conf: '中–高', refs: ['ru13', 'ru14'] },
    { id: 'uk-khaki', cc: 'uk', era: 'E2', year: '1848 → 1902', title: '卡其：从印度边境到全军', tags: ['combat', 'tech', 'culture'],
      what: '1846 年组建的导向团（Corps of Guides）在 Harry Lumsden 主持下，1848 年用尘土色棉布做成宽松军服，成为最早采用卡其的部队；第二次布尔战争后，1902 年卡其哔叽 Service Dress 在全军取代红衣成为作战服。',
      why: 'Lumsden 意识到军服“无论活动还是隐蔽都不实用”，黄灰的尘土色在边境上就是伪装；“khaki”源自波斯语 / 印地斯坦语的“尘土”。无烟火药与远射程步枪让显眼成了负担。美军 1898 年的卡其野战服也被记为“基于英国样式”。',
      dispute: '推广的中间节点（1857、1868、1880 年代苏丹）只有单一来源。', conf: '高（起点与终点）/ 低（中间节点）', refs: ['uk1', 'uk2', 'uk3', 'uk5', 'uk19', 'us2'] },
    { id: 'uk-hsh', cc: 'uk', era: 'E2', year: '1878', title: '本土勤务盔：普鲁士的影子', tags: ['culture', 'politics'],
      what: '1878 年 5 月第 40 号通令批准步兵戴深蓝布面软木盔，顶部有金属尖顶，结束了 1800 年以来的筒帽时代。',
      why: '军服史家 Barthorp 写道：“它像普鲁士式那样带尖顶——正是普鲁士式促成了它的采用”。1870–71 年普法战争后，德式头盔风靡欧洲。',
      dispute: '年份 1877 / 1878 两说；此盔此前已试用数年。', conf: '中', refs: ['uk1', 'uk17', 'uk20'] },
    { id: 'de-feldgrau', cc: 'de', era: 'E3', year: '1842 → 1907', title: '普鲁士的尖顶盔与“原野灰”', tags: ['culture', 'combat', 'tech'],
      what: '1842 年 10 月，普鲁士国王腓特烈·威廉四世以内阁令为大部分步兵引入尖顶盔（Pickelhaube）；1892 年起野战时加浅褐布罩。1907 年 2 月 14 日普鲁士以内阁令采用原野灰（feldgrau）野战服，巴伐利亚、萨克森、符腾堡随后跟进，到 1910 年全面推行；1916 年起尖顶盔逐步被钢盔取代。',
      why: '尖顶盔取意中世纪骑士盔，成了普鲁士—德意志的象征，普法战争后风靡欧洲：英国 1878 年的本土勤务盔直接受它促成，俄国据称 1844 年也采用过。原野灰则是无烟火药时代“隐蔽成为必需”的结果——布尔战争证明鲜艳军服已经过时。',
      dispute: '俄国 1844 年采用尖顶盔只见百科；原野灰的动机说明只有一处来源。', conf: '高（年份）/ 中（传播与动机）', refs: ['de1', 'de2', 'de3', 'de4', 'uk17'] },
    { id: 'cn-1905', cc: 'cn', era: 'E3', year: '1905', title: '号衣退场，但礼服仍戴翎顶', tags: ['combat', 'politics', 'culture'],
      what: '甲午战败后，1895 年新建陆军用德国教官与条令“西法练兵”；1905 年练兵处奏定《陆军服制》：新军常服改为西式，冬深蓝、夏土黄，用“三等九级”军衔标识；大礼服“仍遵旧制”。',
      why: '宽松的号衣不便做洋操，《军服制略》要求“窄小贴身”；步枪时代号衣的颜色与圆布“刚好成为敌人瞄准的靶子”；洋兵以“服章不辨”为由不向华官敬礼，于是要“分设记号”。礼服保留翎顶是向皇权礼制妥协，直到 1910 年禁卫军才改用军帽。',
      dispute: '取法德国还是日本：两说并存，宜写“日、德双重来源”。', conf: '中', refs: ['cn9', 'cn19', 'cn24'] },
    { id: 'uk-brodie', cc: 'uk', era: 'E3', year: '1915–16', title: 'Brodie 钢盔：便宜、好造、先护头顶', tags: ['tech', 'combat'],
      what: 'John L. Brodie 1915 年设计并申请专利，陆军部同年 9 月选定；锰钢一次冲压成型，1916 年 9 月定名 Helmet, Steel, Mark I，约 100 万顶在役。1917 年美国远征军的 M1917 就是它的美制变体。',
      why: '陆军部认为法国钢盔结构复杂、难以快速量产；Brodie 的结论是“相对简单的头盔就能提供合理防护，耐用且便宜”，宽帽檐挡住从头顶上方落下的弹片。代价是颈部与头的下部防护不足、会反光，后来改刷哑光卡其绿。',
      conf: '高', refs: ['uk8', 'uk9', 'us2', 'us6'] },
    { id: 'fr-horizon', cc: 'fr', era: 'E3', year: '1911–1915', title: '“红裤就是法国”——地平线蓝来得太晚', tags: ['culture', 'politics', 'combat'],
      what: '“布尔色”、米灰蓝、1911 年试穿的木犀草绿先后被否决，1914 年 7 月才立法换色；8 月 22 日一天至少 2.5 万法军阵亡；12 月 9 日通知改用地平线蓝，1916 年秋才普及。',
      why: '报刊与议会“爱国地”坚持红裤；木犀草绿被嘲丑陋、像德军原野灰，怕误认。前陆军部长 Étienne 据称说“红裤就是法国！”，梅西米事后称之为“对最显眼颜色盲目而愚蠢的依恋”。地平线蓝由深蓝、浅蓝、白线混纺，德国茜素断供也逼着红色退场。',
      dispute: 'Étienne 语主要经塔奇曼《八月炮火》流传，年份 1911–12 / 1913 两说，议会原始记录未找到；伤亡主因是刺刀冲锋战术还是红裤，宜写“红裤是因素之一”；流行的“一天 2.7 万”未核。', conf: '中–高（试验与否决）/ 低–中（Étienne 语）', refs: ['fr1', 'fr2', 'fr8', 'fr9', 'fr12', 'fr14'] },
    { id: 'fr-adrian', cc: 'fr', era: 'E3', year: '1915', title: 'Adrian 钢盔：第一款大规模配发的现代钢盔', tags: ['tech', 'combat'],
      what: '1915 年冬末先发钢质头盖 cervelière 约 70 万件；Adrian 盔 5 月采用、9 月开始配发，头一年产量逾 700 万；意大利、比利时、塞尔维亚、罗马尼亚、荷兰、俄国相继采用——俄军 1916 年夏换上双头鹰徽后全军列装。',
      why: '堑壕战的头部伤多来自弹片，cervelière 只能挡住约六成；Adrian 盔用薄钢板冲压、分件制造，为的是快和多。',
      dispute: '采用日期 5 月 21 日（军事博物馆）/ 6 月 5 日（国防部“记忆之路”）；“首款”应限定为“首款大规模配发”。', conf: '中–高', refs: ['fr1', 'fr3', 'fr14', 'ru20', 'ru21'] },
    { id: 'ru-1917', cc: 'ru', era: 'E3', year: '1917–1919', title: '从“废除一切外部标志”到布琼尼帽', tags: ['politics', 'culture'],
      what: '1917-12-16 人民委员会法令废除一切官阶、称号、勋章与“一切外部标志”，肩章随之消失；1918 年红军军服竞赛有瓦斯涅佐夫、库斯托季耶夫等画家参与，1919-01 起推广尖顶呢盔“布琼尼帽”（原名“勇士盔”）。',
      why: '法令要“尽快、坚决地消灭军队中旧不平等的一切残余”；新政权需要一套与沙皇军队截然不同、又能唤起俄罗斯民族想象的外观——尖顶呢帽取意古罗斯武士盔。代价是保暖差，苏芬战争后 1940 年被护耳皮帽取代。',
      dispute: '废除日期 12-15 / 12-16，法令未点名“肩章”；布琼尼帽的命令号与日期只见百科；“原为 1915 年柏林胜利阅兵准备”之说被研究者认为缺乏证据。', conf: '高（法令）/ 中（布琼尼帽）', refs: ['ru11', 'ru12', 'ru14', 'ru22'] },
    { id: 'cn-1929', cc: 'cn', era: 'E4', year: '1929', title: '长汀：灰军装、八角帽、红五星、红领章', tags: ['politics', 'culture'],
      what: '1929 年 3 月红四军占长汀，把布匹染灰，赶制 4000 套军装，第一次在一个军的范围内统一着装；红领章缀黑边，纪念列宁逝世 5 周年。1932 年后灰色中山装式上衣 + 八角帽 + 红五星 + 红领章基本定型。',
      why: '统一着装是为了提振士气、便于作战管理；灰色是因为商店没有灰布，只能自己染；毛泽东说两个红领章“代表两面红旗”；样式以苏俄红军的八角帽、“列宁装”为范本。',
      dispute: '八角帽来源至少四说（仿列宁帽、尹德明设计、赵品三设计、冯玉祥赠送），列宁和冯玉祥的国民军都戴过，并非红军首创。', conf: '高（事实）/ 中（起源）', refs: ['cn1', 'cn2', 'cn9', 'cn16', 'cn17'] },
    { id: 'uk-bd', cc: 'uk', era: 'E4', year: '1937', title: 'Battledress：为机械化战争设计的“工作服”', tags: ['tech', 'combat'],
      what: '1937 型 Battledress（齐腰短夹克 + 高腰裤）在二战前夕采用，1939 年起大范围配发；1942 年又推出简化的“1940 型”；一直用到 1950 年代末至 1960 年代。美军 1944 年的“Ike jacket”就仿它的短上衣。',
      why: '国家陆军博物馆称它是“标准的工作服兼作战服……舒适实用”；另一说它按机械化步兵的需要设计、参考当时的羊毛滑雪服，省料、湿了也保暖、便于在车辆里活动（仅一处来源）。',
      dispute: '采用年份写作 1937（型号）、1938 或 1939（配发）都有。', conf: '中', refs: ['uk1', 'uk4', 'uk21', 'us13'] },
    { id: 'us-1943', cc: 'us', era: 'E4', year: '1943–44', title: '分层野战服与“Ike 夹克”', tags: ['combat', 'tech'],
      what: '军需部研制 M-1943 野战服，在地中海战区试用后定型：羊毛内衣、毛衬衫、高领毛衣、夹克、防风外套逐层叠穿；1944 年年中启用短款 M-1944 羊毛野战夹克（“Ike jacket”）。',
      why: '分层可按气温增减，替代笨重的大衣；但欧洲战区起初拒绝换装，直到 1944-11-10 才接受，物资“来得太晚，赶不上那个冬天”，冻伤成为官方医疗战史的专章。M-1944 仿英国 Battledress 以省布，也受艾森豪威尔偏好的定制短夹克影响。',
      dispute: '士兵直到欧战胜利后才普遍领到 Ike 夹克，它实际更多成了战后常服。', conf: '高', refs: ['us13', 'us15'] },
    { id: 'ru-1943', cc: 'ru', era: 'E4', year: '1943', title: '恢复肩章：回到“俄罗斯军事荣誉”', tags: ['politics', 'culture'],
      what: '1943-01-06 最高苏维埃主席团令以肩章取代领章；01-15 国防人民委员 № 25 令规定 2 月 1–15 日全军换装，并把 гимнастёрка 的翻领改成软立领。同年 7 月恢复“军官”称谓。',
      why: '历史学者指出，肩章象征回到俄罗斯军事传统与民族国家，而不是“世界革命”；斯大林说“我们是俄罗斯军事荣誉的继承者”；时机与斯大林格勒的胜利重合，用来强化纪律与指挥员威信，也面向盟国。新式上衣、礼服仿照 1910 年代俄军式样。',
      dispute: '流传的加里宁—斯大林对话轶事来源不明，未采用。', conf: '高（命令原文）/ 中（动机）', refs: ['ru9', 'ru10', 'ru12'] },
    { id: 'fr-lizard', cc: 'fr', era: 'E5', year: '1947–1963', title: '“蜥蜴纹”：伞兵的迷彩与政治', tags: ['combat', 'politics'],
      what: 'M1947/51 是法国首款量产的 lizard 迷彩罩衫，先由空降部队在印度支那使用，M1947/56 为最终改型；葡萄牙 1960 年先给精锐营、1963 年全军采用了它的版本。',
      why: '浅绿底上的横向刷痕适合丛林与灌木；从印度支那到阿尔及利亚，它成了伞兵精英的身份标志。常见说法是它在 1963 年 1 月撤装，因为让人联想到 1961 年伞兵参与的将军叛乱。',
      dispute: '撤装的政治原因只有百科转引一部 Osprey（低），实务原因说未找到来源；1979 年吉布提的照片里仍有部队穿 lizard；“受英国 Denison 罩衫启发”只见百科（低）。', conf: '中（外观与年代）/ 低（撤装原因）', refs: ['fr10b', 'fr17', 'fr24'] },
    { id: 'cn-1955', cc: 'cn', era: 'E5', year: '1955', title: '55 式：“主要参照苏联”与船形帽之争', tags: ['politics', 'culture', 'combat'],
      what: '1955-09-27 授衔，10-01 起实行 55 式：肩章、大檐帽、礼服与常服两个系列，士兵戴船形帽。1953 年贺龙主持的军服改革小组收集了苏、美、朝与北洋、国民党军的样品。',
      why: '军衔“主要参照苏联”，但出于“勤俭建国”不照搬兵种元帅；1956 年总参文件说新服装“继承了我军各个时期军服样式的特点”，同时“部分地采用了苏联和各人民民主国家及国际上通用的”样式。士兵帽不设帽檐，是因为“卧射时妨碍视线”，且便于戴钢盔。回调：船形帽被士兵认为“戴正了像和尚，歪戴着像流氓”，1958 年决定、1959 年改戴解放帽。',
      dispute: '55 式是两类还是三类；“1958 年起礼服停穿”未能核实。', conf: '高', refs: ['cn2', 'cn12', 'cn13', 'cn14'] },
    { id: 'cn-1965', cc: 'cn', era: 'E6', year: '1965', title: '取消军衔：“三点红”', tags: ['politics', 'culture'],
      what: '1965-05-22 全国人大常委会决定取消军衔制，06-01 实施；全军换 65 式：解放帽 + 全红五星帽徽 + 全红领章，官兵服装基本相同，只靠口袋数量区分。',
      why: '决定原文只有一句“取消中国人民解放军军衔制度”，没有写理由；后来的官方叙述称这是“受‘左’的思想的干扰”。符号上回到 1929 年红军的红星与红领章；把官兵差别压到口袋数量，是“官兵一致”的外在表现（本页解读）。代价是三军仪仗队此后约 20 年没有礼服。',
      dispute: '“一颗红星头上戴，革命红旗挂两边”是流传的俗语，出处未能核实。', conf: '高（事实）/ 中（动机）', refs: ['cn1', 'cn2', 'cn14', 'cn15', 'cn16', 'cn23'] },
    { id: 'uk-dpm-mtp', cc: 'uk', era: 'E6', year: '1968 → 2010', title: '从欧洲林地到赫尔曼德的“绿区”：DPM → MTP', tags: ['combat', 'tech'],
      what: 'DPM 迷彩布 1968 年投产、1969 年开始配发，1970 年代普及；2009 年 12 月国防部公布 MTP，作为紧急作战需求 6 个月、约 25 万英镑研制，2010 年起先发给赴阿富汗部队，2011 年起推广到三军。',
      why: '赫尔曼德河沿岸是狭长的灌溉“绿区”，两侧是荒漠，士兵一天多次进出，只好混穿林地与沙漠 DPM；国防部用航拍与科学摄影取色，再用计算机模拟。MTP 以 Crye Precision 的 MultiCam 为基础、采用 DPM 的斑块形状，“在最广泛的环境中表现最好”。',
      dispute: 'DPM 起始年份（1963 / 1966 / 1968 / 1970 年代）；MTP 首发 3 月或 4 月。', conf: '高（MTP）/ 中（DPM 起始）', refs: ['uk6', 'uk10', 'uk11', 'uk12', 'uk13', 'uk22', 'uk24'] },
    { id: 'ru-afghanka', cc: 'ru', era: 'E6', year: '1984–88', title: '“阿富汗卡”：战场倒逼出来的野战服', tags: ['combat', 'tech'],
      what: '1984 年 7 月苏联部长会议 № 722-158 决议与国防部 № 0145 令批准 1984 年式野战服，先发驻阿部队；1988-03-04 № 250 令最终确定。',
      why: '1969 年式长大衣与封闭式上衣在装甲车里施展不开；中央被服局总结阿富汗经验，改成短夹克、多口袋、肘部加固、透气帽。',
      dispute: '1969 年废止套头衫、理由是便于伤员脱衣，只有百科一处（低）。', conf: '中', refs: ['ru23', 'ru15'] },
    { id: 'cn-1988', cc: 'cn', era: 'E6', year: '1984–88', title: '恢复军衔与“礼 / 常 / 作训”三分', tags: ['politics', 'combat', 'tech'],
      what: '1984 年 1 月军委批准 85 式（恢复大檐帽与军种肩章、领章），并要求逐步分出礼服、常服、作训服；1988-10-01 恢复军衔，87 式分礼服、常服、作训服，作训服首次包含迷彩。',
      why: '改革开放后，“体制单一、样式呆板、面料落后”的问题突出；设计时研究了 27 个国家的军服样品、测量了 1.5 万名官兵的体型；迷彩借鉴北约三色丛林迷彩。85 式只标军种不标衔的肩章，在形制上为恢复军衔做了铺垫（本页解读）。',
      dispute: '受经费所限，87 式礼服没有发到部队（仅一处来源）。', conf: '高（事实）/ 中（解读）', refs: ['cn1', 'cn2', 'cn5', 'cn14'] },
    { id: 'ca-cadpat', cc: 'ca', era: 'E7', year: '1997–2002', title: 'CADPAT → MARPAT：数码迷彩与“专属迷彩”', tags: ['tech', 'culture'],
      what: '加拿大 1990 年代中期开始试验电脑设计的像素迷彩 CADPAT，1996–97 年定型，2001 年起正式配发（温带型），2002 年推出沙漠型；美国海军陆战队以它为基础研制 MARPAT，2002 年 1 月亮相、2004 年完成换装。',
      why: '像素化小色块在远近两种距离上都能破坏轮廓；MARPAT 的图案由政府申请专利、禁止商售，迷彩从此也成了军种的识别标志——此后美国各军种纷纷自研专属迷彩。',
      dispute: 'CADPAT 定型与配发年份各处略有出入（1996 / 1997 / 2001）；“第一种实际配发的数码迷彩”之说出自百科转引。', conf: '中', refs: ['x1', 'x2', 'us17', 'us18'] },
    { id: 'us-ucp', cc: 'us', era: 'E7', year: '2004–2019', title: 'UCP 的失败与 OCP', tags: ['combat', 'politics', 'tech'],
      what: '陆军 2004–05 年以 UCP“通用迷彩”ACU 替换 BDU；2009 年国会在补充拨款法中要求为阿富汗提供合适迷彩；2010 年起阿富汗部队改穿 OEF-CP（MultiCam）；2015-07-01 起配发 OCP，2019-10-01 UCP 退役。',
      why: 'UCP 想用一种灰绿图案“通吃”各种地形，士兵反映局限明显；替代方案经多地形、多季节、昼夜的“最全面”测试后选定。代价是十年内两次全军换装，并由国会立法介入。',
      dispute: '“UCP 花费约 50 亿美元”等数字没有官方来源，未写入；GAO-12-707 报告原文未能读取。', conf: '高（时间线）/ 中（失败原因）', refs: ['us7', 'us8', 'us18'] },
    { id: 'cn-2007', cc: 'cn', era: 'E7', year: '2007 → 2021', title: '从“军种色”到“地形色”', tags: ['tech', 'combat', 'culture'],
      what: '2007 年 8 月 1 日起换发 07 式：4 个系列、644 个品种，陆军松枝绿、海军深藏青 / 白、空军蓝灰，数码迷彩按军种配发；2021 年冬起换发 21 式：迷彩按地形配发，增加特勤作训服与作业服。',
      why: '07 式的松枝绿掺入红军、八路军的灰调来“继承传统”，按东方人肤色挑选并与行业制服拉开区别，数码迷彩强调自主知识产权。21 式的背景是官方评论承认 07 式迷彩“过于强调军种区别”——海军陆战队在朱日和荒漠演习仍穿海洋迷彩，因此改为按地形配发、标志低可视化。',
      dispute: '21 式迷彩品种数：官方“丛林、荒漠等”，评论文章称五种。', conf: '高', refs: ['cn2', 'cn3', 'cn4', 'cn5', 'cn6', 'cn7'] },
    { id: 'us-agsu', cc: 'us', era: 'E8', year: '2018', title: 'AGSU：把“pinks and greens”请回来', tags: ['culture'],
      what: '2018 年 11 月陆军宣布 Army Green Service Uniform 为日常职业场合的常服，蓝色 ASU 回归礼服；2027-10-01 为强制持有日。',
      why: '官方明言是“重新启用‘最伟大的一代’所穿的制服”，给士兵一套尊重传统的职业装——在作战服高度技术化之后，常服反而回头去找二战的记忆。',
      dispute: '“提升形象、帮助征兵”的动机常被提及，但未在官方原文中核到。', conf: '高', refs: ['us12', 'us5'] },
    { id: 'fr-bme', cc: 'fr', era: 'E8', year: '2016–2024', title: 'BME：两套迷彩变一套', tags: ['tech', 'combat'],
      what: '2016 年 3 月开始研制，2022-05-12 公布，6 色，取代沿用约 30 年的中欧林地迷彩与沙漠迷彩（另保留雪地型）；2024 年 12 月首批配发。',
      why: '官方理由是提高隐蔽性（“被发现的延迟”提高 25%）、多战区通用、后勤上两套变一套，并在 30 年后更新视觉形象；由陆军技术处设计、军需部门与法国企业量产。',
      conf: '高', refs: ['fr20', 'fr22', 'fr23'] }
  ];

  /* ---------- 谁影响了谁 ---------- */
  var FLOWS = [
    { year: 'c.1700', from: '西欧', to: '俄国', what: '彼得一世按欧洲样式引入 кафтан、翻袖口与绑腿', conf: '中', refs: ['ru14'] },
    { year: '1778–79', from: '法国', to: '美国', what: '法国援助的蓝、棕成衣与向法国订购的军服物资，塑造了“大陆军蓝”', conf: '高', refs: ['us1', 'us3'] },
    { year: '1844', from: '普鲁士', to: '俄国', what: '尖顶盔（据百科；俄方档案本轮未核）', conf: '低', refs: ['de1'] },
    { year: '1796–97', from: '普鲁士', to: '俄国', what: '保罗一世恢复普鲁士式长外衣、发辫与扑粉', conf: '中–高', refs: ['ru14', 'ru19'] },
    { year: '1815', from: '法兰西帝国近卫军', to: '英国', what: '熊皮帽与燃烧手榴弹帽徽（滑铁卢战利荣誉）', conf: '高', refs: ['uk7'] },
    { year: '1848 →', from: '英属印度', to: '英国 → 各国', what: '卡其：导向团首创，1902 年成为英军作战服；美军 1898 年卡其野战服“基于英国样式”', conf: '高', refs: ['uk2', 'uk19', 'us2'] },
    { year: '1850 年代', from: '法国', to: '美国', what: 'frock coat 剪裁与 kepi 式便帽；南北战争中甚至直接进口法国猎兵服', conf: '中', refs: ['fr27', 'us5'] },
    { year: '1878', from: '普鲁士', to: '英国', what: '本土勤务盔的尖顶', conf: '中', refs: ['uk17', 'uk20'] },
    { year: '1895', from: '德国', to: '清军', what: '新建陆军聘德国教官、用德国条令，自强军仿德制统一军服', conf: '高', refs: ['cn19', 'cn9'] },
    { year: '1905–12', from: '日本（与德国）', to: '清末新军 / 北洋', what: '新军服制与北洋常服、徽章“基本照搬日本陆军”，也有德式来源', conf: '中', refs: ['cn9', 'cn24'] },
    { year: '1915–16', from: '法国', to: '俄国等', what: 'Adrian 钢盔：意、比、塞、罗、荷、俄相继采用', conf: '高', refs: ['fr3', 'ru20', 'ru21'] },
    { year: '1917', from: '英国', to: '美国', what: 'M1917 钢盔是 Brodie Mark I 的美制变体', conf: '高', refs: ['us2', 'us6'] },
    { year: '1929–32', from: '苏俄红军', to: '中国工农红军', what: '八角帽与“列宁装”范本、红星', conf: '中', refs: ['cn16', 'cn17'] },
    { year: '1930 年代', from: '德国', to: '国民革命军', what: '军事顾问、圆顶加围布帽、M35 钢盔', conf: '中–高', refs: ['cn10', 'cn11'] },
    { year: '1939 →', from: '英国', to: '英联邦与盟国；美国', what: 'Battledress 被多国采用或仿制；1944 年美军 Ike 夹克仿其短上衣', conf: '中', refs: ['uk4', 'uk21', 'us13'] },
    { year: '1955', from: '苏联', to: '中国', what: '55 式军衔“主要参照苏联”，服装“部分地采用了苏联”样式', conf: '高', refs: ['cn12', 'cn13'] },
    { year: '1960–63', from: '法国', to: '葡萄牙等', what: 'lizard 迷彩：葡萄牙版本 1960 年先配精锐营、1963 年全军；以色列用过法国剩余品', conf: '高 / 中', refs: ['fr24', 'fr17', 'fr10b'] },
    { year: '1980 年代', from: '北约', to: '中国', what: '87 式迷彩受“三色丛林迷彩”启发', conf: '中', refs: ['cn5'] },
    { year: '2001–02', from: '加拿大', to: '美国海军陆战队', what: 'CADPAT → MARPAT 数码迷彩', conf: '中', refs: ['x1', 'us17'] },
    { year: '2010', from: '美国（Crye MultiCam）', to: '英国', what: 'MTP 以 MultiCam 为基础，采用 DPM 的斑块形状', conf: '中–高', refs: ['uk12', 'uk24'] }
  ];

  /* ---------- 参考（按国家分组）---------- */
  var REFS = {
    cn: [
      ['cn1', '张磊：《永不褪色的军装》，《人民日报》2017-08-01 第 12 版', 'http://military.people.com.cn/n1/2017/0801/c1011-29440220.html'],
      ['cn2', '江西服装学院服装博物馆：《中国人民解放军军服演进史话》，2008', 'https://museum.jift.edu.cn/info/1085/1399.htm'],
      ['cn3', '尹建航：《解放军 07 式新军服分礼服常服等四大系列》，2007-07-03（新浪转载）', 'http://mil.news.sina.com.cn/2007-07-03/0629452477.html'],
      ['cn4', '朱水安、范炬炜：《中国 07 式军服有六特点 加入红军八路军军服色调》，央视国际 2007-07-03', 'http://news.cctv.com/china/20070703/102783.shtml'],
      ['cn5', '《揭秘“星空迷彩”》，《中国青年报》2019-11-21（中新网转载）', 'https://www.chinanews.com/m/mil/2019/11-21/9013252.shtml'],
      ['cn6', '国防部：《国防部介绍 21 式作训服和作业服换发情况》，2021-12-30', 'http://www.mod.gov.cn/gfbw/xwfyr/16015691.html'],
      ['cn7', '新华社：《全军部队陆续换发 21 式作训服和作业服》，2021-12-30', 'http://www.news.cn/2021-12/30/c_1128218724.htm'],
      ['cn8', '《解放军报》2021-12-19 换发消息（观察者网转述）', 'https://www.guancha.cn/military-affairs/2021_12_20_619180.shtml'],
      ['cn9', '胡彦青、张竞琼：《晚清及民国时期陆军军服的近代化》，《浙江理工大学学报（社会科学版）》38(1)，2017', 'http://xuebao.zstu.edu.cn/OA/pdfdow.aspx?Sid=20170208'],
      ['cn10', '《漫话黄埔军服及枪械（续）》，《黄埔》2019 年第 5 期', 'http://www.huangpu.org.cn/hpzz/hpzz201905/202001/t20200107_12230816.html'],
      ['cn11', '《抗战时期中国军队的单兵装具》，澎湃新闻·私家历史', 'https://www.thepaper.cn/newsDetail_forward_1646096'],
      ['cn12', '《揭秘 1955 授衔典礼“幕后”：军服、标志焕然一新》，北京日报 / 京报网 2025-10-13', 'https://news.bjd.com.cn/2025/10/13/11349911.shtml'],
      ['cn13', '《解放军船形帽为什么只戴了三年多就被取消了》，新浪军事 2018-05-02（源自中国军网）', 'https://mil.sina.cn/2018-05-02/detail-ifzyqqip8566725.d.html'],
      ['cn14', '人民网：《中国人民解放军军衔制》，2014-07-12', 'http://military.people.com.cn/n/2014/0712/c1011-25272225.html'],
      ['cn15', '《全国人民代表大会常务委员会关于取消中国人民解放军军衔制度的决定》（1965-05-22），《国务院公报》1965 年第 8 期', 'https://zh.wikisource.org/wiki/%E5%85%A8%E5%9B%BD%E4%BA%BA%E6%B0%91%E4%BB%A3%E8%A1%A8%E5%A4%A7%E4%BC%9A%E5%B8%B8%E5%8A%A1%E5%A7%94%E5%93%A1%E4%BC%9A%E5%85%B3%E4%BA%8E%E5%8F%96%E6%B6%88%E4%B8%AD%E5%9B%BD%E4%BA%BA%E6%B0%91%E8%A7%A3%E6%94%BE%E5%86%9B%E5%86%9B%E8%A1%94%E5%88%B6%E5%BA%A6%E7%9A%84%E5%86%B3%E5%AE%9A'],
      ['cn16', '《第一套红军军服的诞生：八角帽的来历说法不一》，《解放日报》2010-02-26（中新网转载）', 'https://www.chinanews.com.cn/cul/news/2010/02-26/2139995.shtml'],
      ['cn17', '中国军网：《红军的符号：红星八角帽》，2016-10-10', 'https://photo.81.cn/zhuanti/2016-10/10/content_7293146.htm'],
      ['cn18', '故宫博物院：《黄色缎绣金龙纹铜钉乾隆帝御用棉甲》藏品页', 'https://www.dpm.org.cn/collection/defense/234700.html'],
      ['cn19', '天津文化信息网：《小站练兵》', 'http://hhjyy.tjl.tj.cn/shwh/lywh/mrgj/yuan-shi-kai/lssj-xzlb.htm'],
      ['cn20', '中央军委：《中国人民解放军内务条令》（军令〔2025〕18 号）', 'http://www.mod.gov.cn/gfbw/qwfb/16371391.html'],
      ['cn21', '中央军委：《中国人民解放军内务条令（试行）》（军令〔2018〕58 号）', 'http://www.mod.gov.cn/gfbw/qwfb/4809634.html'],
      ['cn22', '潘珊菊：《三军仪仗队新式礼宾服亮相》，《京华时报》2014-08-20', 'http://news.sina.com.cn/c/2014-08-20/025030712189.shtml'],
      ['cn23', '人民网组图：《中国人民解放军三军仪仗队礼服的历史变迁》，2014-08-29', 'http://military.people.com.cn/n/2014/0829/c1011-25564952.html'],
      ['cn24', '中文维基百科《中华民国军服》（引樊学庆《1905 年新军服制述论》，《军事历史研究》2007(3)；《民国军服图志》）——仅作线索', ''],
      ['cn25', '战甲军品资料网：《解放军 55 式军服装备始末》（爱好者资料，辅助）', 'https://www.junpin360.com/html/2012-03-04/381.html']
    ],
    us: [
      ['us1', 'Founders Online / U.S. National Archives, “General Orders, 2 October 1779”', 'https://founders.archives.gov/documents/Washington/03-22-02-0489'],
      ['us2', 'David Cole / U.S. Army Center of Military History, “Survey of U.S. Army Uniforms, Weapons and Accoutrements”, 2007', 'https://history.army.mil/html/museums/uniforms/survey_uwa.pdf'],
      ['us3', 'U.S. National Archives, “Threads of Independence: The Evolution of the Iconic Blue Uniform”', 'https://artsandculture.google.com/story/threads-of-independence-the-evolution-of-the-iconic-blue-uniform-u-s-national-archives/WQUBpsvTZriEbQ'],
      ['us4', 'Smithsonian NMAH, “George Washington’s Uniform”', 'https://www.si.edu/object/george-washingtons-uniform:nmah_434863'],
      ['us5', 'Wikipedia, “Uniforms of the United States Army”（辅助）', 'https://en.wikipedia.org/wiki/Uniforms_of_the_United_States_Army'],
      ['us6', 'Smithsonian Magazine, “How the Military Helmet Evolved From a Hazard to a Bullet Shield”, 2017', 'https://www.smithsonianmag.com/smithsonian-institution/how-military-helmet-evolved-hazard-bullet-shield-180963319/'],
      ['us7', 'U.S. Army, “Army to field Operational Camouflage Pattern for uniforms”, 2015-06-01', 'https://www.army.mil/article/149612/army_to_field_operational_camouflage_pattern_for_uniforms'],
      ['us8', 'U.S. Army, “ACU pattern officially retired; new uniform improvements on the way”, 2019-10-10', 'https://www.army.mil/article/228411/acu_pattern_officially_retired_new_uniform_improvements_on_the_way'],
      ['us9', 'Smithsonian, CivilWar@Smithsonian “Union Uniform” / “Confederate Uniform”', 'https://civilwar.si.edu/soldiering_union_uniform.html'],
      ['us10', 'Smithsonian NMAH 藏品记录：Army Sack Coat, Model 1858；Herringbone Twill, Model 1943', ''],
      ['us11', 'Imperial War Museums, “Helmet, Kevlar, PASGT: US Army”', 'https://www.iwm.org.uk/collections/item/object/30119059'],
      ['us12', 'U.S. Army, “Army Uniforms and Grooming Guide”', 'https://www.army.mil/uniforms/'],
      ['us13', 'Imperial War Museums, “Jacket, Field, Wool, OD, M-1944”', 'https://www.iwm.org.uk/collections/item/object/30095091'],
      ['us14', 'Army Times, “The end of the Green Service Uniform: 1954–2015”, 2015-10-01', 'https://www.armytimes.com/news/your-army/2015/10/01/the-end-of-the-green-service-uniform-1954-2015/'],
      ['us15', 'AMEDD Center of History & Heritage, “Cold Injury, Ground Type”, Chapter 7', 'https://achh.army.mil/history/book-wwii-coldinjury-chapter07/'],
      ['us16', 'U.S. Army, “Air Force senior leaders update OCP uniform guidance”, 2019-04-24', 'https://www.army.mil/article/220786/air_force_senior_leaders_update_ocp_uniform_guidance'],
      ['us17', 'Wikipedia, “MARPAT”（引 MCB Quantico 2002 等，辅助）', 'https://en.wikipedia.org/wiki/MARPAT'],
      ['us18', 'Wikipedia, “Battle Dress Uniform”（引 CMH DAHSUM FY1982，辅助）', 'https://en.wikipedia.org/wiki/Battle_Dress_Uniform'],
      ['us19', 'U.S. GAO, GAO-12-707 “Warfighter Support: DOD Should Improve Development of Camouflage Uniforms…”, 2012（本轮未能读取）', 'https://www.gao.gov/assets/gao-12-707.pdf'],
      ['us20', 'U.S. Army, “Elements of Twilight Tattoo: Uniforms of The Old Guard Fife and Drum Corps”', 'https://www.army.mil/article/79850/elements_of_twilight_tattoo_uniforms_of_the_old_guard_fife_and_drum_corps'],
      ['x1', 'Wikipedia, “CADPAT”（引 HyperStealth 等，辅助）', 'https://en.wikipedia.org/wiki/CADPAT'],
      ['x2', 'Camopedia, “Canada”', 'https://www.camopedia.org/index.php/Canada']
    ],
    ru: [
      ['ru1', '俄罗斯联邦总统令 2010-03-11 № 293《О военной форме одежды…》', 'http://www.kremlin.ru/acts/bank/30748'],
      ['ru2', '俄联邦国防部长令 2020-10-09 № 525《Об утверждении Правил ношения военной формы одежды…》', 'https://rulaws.ru/acts/Prikaz-Ministra-oborony-RF-ot-09.10.2020-N-525/'],
      ['ru3', '俄罗斯联邦总统令 1994-05-23 № 1010《О военной форме одежды и знаках различия по воинским званиям》', 'https://base.garant.ru/184184/'],
      ['ru5', '《Аргументы и Факты》：《Как менялась военная форма в современной России》，2012-11-21', 'https://aif.ru/society/army/kak_menyalas_voennaya_forma_v_sovremennoy_rossii_voprosy_i_otvety'],
      ['ru6', 'РБК Life：《Кого одевал Валентин Юдашкин》，2023-05-02', 'https://www.rbc.ru/life/news/64510fa39a7947185570f2c6'],
      ['ru7', 'ТАСС：《Боевая экипировка “Ратник” принята на вооружение》，2017-08-23', 'https://tass.ru/armiya-i-opk/4500167'],
      ['ru8', 'Рамблер / ТАСС：《Первая серийная партия экипировки «Ратник» поступила в войска》，2015-05-23', 'https://news.rambler.ru/politics/30300477-ekipirovka-ratnik-postupila-v-voyska'],
      ['ru9', '国防人民委员令 1943-01-15 № 25 原文（档案著录：РГВА ф.4 оп.12 д.107；另见 Викитека 录文）', 'https://docs.historyrussia.org/ru/nodes/187505'],
      ['ru10', '苏联最高苏维埃主席团令 1943-01-06《О введении новых знаков различия…》原文（Викитека）', ''],
      ['ru11', '人民委员会法令 1917-12-16《Об уравнении всех военнослужащих в правах》原文', ''],
      ['ru12', 'А. Смирнов：《Как нашей армии были возвращены погоны и офицеры》，《Родина》2018-01-07', 'https://rodina-history.ru/2018/01/07/rodina-pogony.html'],
      ['ru13', '俄罗斯国家历史博物馆：专题展《Александр III — история становления императора》', 'https://shm.ru/aleksandr/'],
      ['ru14', 'РИА Новости：《Что носили военные и почему это важно》，2021-06-12（莫斯科军服博物馆访谈）', 'https://ria.ru/20210612/muzey-1736497773.html'],
      ['ru15', '俄文维基百科《Гимнастёрка》（辅助）', 'https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D0%BC%D0%BD%D0%B0%D1%81%D1%82%D1%91%D1%80%D0%BA%D0%B0'],
      ['ru18', '图拉国家兵器博物馆：展览《Честь мундира》', 'https://museum-arms.ru/exhibitions/e/vystavka-cest-mundira-istoriia-rossiiskix-voisk-xviii-nacala-kx'],
      ['ru19', 'А. Козлов：《Русский военный мундир конца XVIII в. в собрании Исторического музея》，国家历史博物馆博客', 'https://blog.mediashm.ru/?p=6171'],
      ['ru20', 'В. Пельш：《Каски, шлемы и другие защитные головные уборы русской армии》，Культура.РФ', 'https://www.culture.ru/s/vopros/kaski/'],
      ['ru21', '罗斯托夫州方志博物馆：《Музейный предмет: каска Адриана》，2023', 'https://www.rostmuseum.ru/museum/blog/muzeynyy-predmet-kaska-adriana/'],
      ['ru22', '俄文维基百科《Будёновка》（辅助）', 'https://ru.wikipedia.org/wiki/%D0%91%D1%83%D0%B4%D1%91%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0'],
      ['ru23', 'А. В. Печейкин：《По опыту боёв в Афганистане》，《Военно-исторический журнал》2014', 'https://history.milportal.ru/po-opytu-boyov-v-afganistane/'],
      ['ru24', 'forma-odezhda.com：《ЗДУ – ЕМР – Цифровая флора》（军服百科，辅助）', 'https://forma-odezhda.com/encyclopedia/zdu-emr-cifrovaya-flora-kamuflyazh/'],
      ['ru25', 'forma-odezhda.com：《Форма офицеров армии и флота СССР 1955 г.》（军服百科，辅助）', 'https://forma-odezhda.com/encyclopedia/forma-oficerov-armii-i-flota-sssr-1955-g/']
    ],
    uk: [
      ['uk1', 'UK Ministry of Defence, Army Dress Regulations (All Ranks), Part 1（2017 年依信息自由法 FOI2017/03109 公开的版本）', ''],
      ['uk2', 'National Army Museum, “The North-West Frontier”', 'https://www.nam.ac.uk/explore/north-west-frontier-india'],
      ['uk3', 'National Army Museum, “The Uniform and Equipment of 1914”', 'https://ww1.nam.ac.uk/937/news/uniform-equipment-1914/'],
      ['uk4', 'National Army Museum, “Army fashion statements”', 'https://www.nam.ac.uk/explore/armys-been-responsible-many-fashion-statements'],
      ['uk5', 'National Army Museum, “Camouflage Through Time”（视频文字稿），2020', 'https://www.nam.ac.uk/sites/default/files/learning-resource-files/2020-08/20200608_Transcript-CamouflageThroughTime_FINAL.pdf'],
      ['uk6', 'National Army Museum, “The evolution of military camouflage”', 'https://www.nam.ac.uk/whats-on/evolution-military-camouflage'],
      ['uk7', 'National Army Museum, “The Grenadier Guards”', 'https://www.nam.ac.uk/explore/grenadier-guards'],
      ['uk8', 'National Army Museum, “The Brodie Helmet”', 'https://ww1.nam.ac.uk/1904/news/brodie-helmet/'],
      ['uk9', 'Imperial War Museums, “Steel Helmet, MK I Brodie pattern”', 'https://www.iwm.org.uk/collections/item/object/30090820'],
      ['uk10', 'Imperial War Museums, “Trousers, Combat Dress, 1968 pattern (DPM)”', 'https://www.iwm.org.uk/collections/item/object/30094716'],
      ['uk11', 'CNN, “British troops to get first new camouflage in 40 years”, 2009-12-20', 'http://www.cnn.com/2009/WORLD/europe/12/20/uk.army.camouflage/index.html'],
      ['uk12', 'The Register, “British troops to get new all-terrain camouflage kit”, 2009-12-21', 'https://www.theregister.com/offbeat/2009/12/21/british-troops-to-get-new-all-terrain-camouflage-kit/1536665'],
      ['uk13', 'UK MoD, “Introduction of Personal Clothing System”, 2011-02-07（Soldier Systems Daily 转载）', 'http://soldiersystems.net/2011/02/08/introduction-of-personal-clothing-system/'],
      ['uk14', 'Soldier（英国陆军杂志），2015 年 7 月号“Virtus revealed”', 'https://soldier.army.mod.uk/media/jmcpfogs/soldier-jul-2015.pdf'],
      ['uk15', 'Airborne Assault Museum / ParaData, “VIRTUS”', 'https://paradata.org.uk/content/4663417-virtus'],
      ['uk16', 'Forces News, “British Soldiers Test New Lighter Body Armour”', 'https://www.forcesnews.com/services/army/british-soldiers-test-new-lighter-body-armour'],
      ['uk17', 'Military Sun Helmets, “The British Home Service Helmet”（引 Barthorp 与 1878 年第 40 号通令）', 'http://www.militarysunhelmets.com/2013/the-british-home-service-helmet'],
      ['uk18', 'Wikipedia, “Red coat (military uniform)”（辅助）', 'https://en.wikipedia.org/wiki/Red_coat_(military_uniform)'],
      ['uk19', 'Wikipedia, “Khaki”（引 JSAHR 82 (2004)，辅助）', 'https://en.wikipedia.org/wiki/Khaki'],
      ['uk20', 'Wikipedia, “Shako”（辅助）', 'https://en.wikipedia.org/wiki/Shako'],
      ['uk21', 'Wikipedia, “British Battledress”（引 Jewell, Osprey MAA-112，辅助）', 'https://en.wikipedia.org/wiki/British_Battledress'],
      ['uk22', 'Wikipedia, “Disruptive Pattern Material”（辅助）', 'https://en.wikipedia.org/wiki/Disruptive_Pattern_Material'],
      ['uk23', 'Wikipedia, “Denison smock”（辅助）', 'https://en.wikipedia.org/wiki/Denison_smock'],
      ['uk24', 'Wikipedia, “Multi-Terrain Pattern”（辅助）', 'https://en.wikipedia.org/wiki/Multi-Terrain_Pattern'],
      ['uk25', 'Wikipedia, “Service Dress (British Army)”（引 Barthorp，辅助）', 'https://en.wikipedia.org/wiki/Service_Dress_(British_Army)'],
      ['uk26', 'All About History, “Who were Britain’s original Red Coats?”', 'https://www.historyanswers.co.uk/history-of-war/who-were-britains-original-red-coats/'],
      ['uk27', 'Historic UK, “Fashion in the English Civil War”', 'https://www.historic-uk.com/CultureUK/Fashion-English-Civil-War/'],
      ['uk28', 'National Army Museum Online Collection 藏品标题：Pattern 1968 combat smock（1983-06-2-1）、Battle dress blouse 1940（1982-06-41-3）等', ''],
      ['uk30', 'Wikimedia Commons, Category: Cloathing Book 1742 图版', 'https://commons.wikimedia.org/wiki/Category:British_Army_Uniform_Illustrations_in_the_Cloathing_Book_1742'],
      ['uk31', 'Wikimedia Commons, File:British soldier during Operation Granby.jpg 图片说明（辅助）', 'https://commons.wikimedia.org/wiki/File:British_soldier_during_Operation_Granby.jpg'],
      ['uk32', 'The Royal Clothing Warrant, 1751（转录）', 'https://fifedrum.org/crfd/1751.htm'],
      ['uk33', 'His Majesty’s Warrant … 1768（TNA WO 30/13B，转录）', 'https://www.redsandrevs.co.uk/clothing-warrant-1768'],
      ['uk35', 'Imperial War Museums, “Blouse, Battledress, 1949 pattern”', 'https://www.iwm.org.uk/collections/item/object/30101222']
    ],
    fr: [
      ['fr1', 'Musée de l’Armée, « L’uniforme du fantassin français en 1914 et 1916 »（fiche-objet）', 'https://www.musee-armee.fr/fileadmin/user_upload/Documents/Support-Visite-Fiches-Objets/Fiches-1914-1918/MA_fiche-objet-uniformes-14-18.pdf'],
      ['fr2', 'Ministère des Armées / Chemins de mémoire, « Uniformes : la voix de l’artiste »', 'https://www.cheminsdememoire.gouv.fr/fr/uniformes-la-voix-de-lartiste'],
      ['fr3', 'Ministère des Armées / Chemins de mémoire, « Louis Adrian »', 'https://www.defense.gouv.fr/chemins-memoire/histoire-memoires/personnalites/personnalites-lettre-lettre/louis-adrian'],
      ['fr4', 'François Houdecek（Fondation Napoléon）, « Le paquetage du fantassin napoléonien »', 'https://www.napoleon.org/histoire-des-2-empires/articles/le-paquetage-du-fantassin-napoleonien/'],
      ['fr5', 'P. F. d’Isnard, « État général des uniformes … le 21 février 1779 »（Gallica）', 'https://gallica.bnf.fr/ark:/12148/bpt6k313642n'],
      ['fr6', '« Uniformes de l’infanterie françoise … 21 Fevrier 1779 »（WorldCat OCLC 59708215）', ''],
      ['fr7', '« Le pantalon garance, l’armée et la société française (1829-1914) », Revue historique des armées n°157, 1984（仅见题名）', 'https://www.persee.fr/doc/rharm_0035-3299_1984_num_157_4_7394'],
      ['fr8', 'Jean-Claude Bernier, « L’alizarine est-elle responsable du désastre du 22 août 1914 ? », Société Chimique de France, 2014', ''],
      ['fr9', 'Barbara W. Tuchman, The Guns of August, 1962（转引梅西米回忆录）', 'https://www.goodreads.com/notes/40779082-the-guns-of-august/55091073-al/c17b7b41-3474-4da8-af65-6b1d3e4794e8'],
      ['fr10', 'Wikipedia, « Pantalon rouge »（辅助）', 'https://en.wikipedia.org/wiki/Pantalon_rouge'],
      ['fr10b', 'Wikipedia, « Lizard (camouflage) »（引 Windrow, Osprey MAA 300 等，辅助）', 'https://en.wikipedia.org/wiki/Lizard_(camouflage)'],
      ['fr11', '« Combattre en habit bleu ? … colorants sous la Révolution et l’Empire », Parlement[s] 2021/3（仅见题名）', ''],
      ['fr12', 'Herodote.net, « 22 août 1914 – Massacres à Morhange, Charleroi et Rossignol », 2018', ''],
      ['fr13', 'R. Carpentier / R. Guyader, « Histoire du képi blanc », legion-etrangere.com', 'https://www.legion-etrangere.com/mdl/page.php?id=740'],
      ['fr14', 'SNHPG, « Du bleu horizon au bleu gendarme », 2022', 'https://www.force-publique.net/2022/03/17/du-bleu-horizon-au-bleu-gendarme/'],
      ['fr15', 'Promotion Capitaine Beaumont（圣西尔届别网站），« Le G.U. »', 'http://www.promocnebeaumont.fr/saint-cyr/symboles-et-attributs/le-gu/'],
      ['fr16', 'Bob 词典, « casoar (depuis 1855) »', 'https://www.languefrancaise.net/Bob/58447'],
      ['fr17', 'Imperial War Museums, « Smock (camouflaged), M1947/56: French »', 'https://www.iwm.org.uk/collections/item/object/30097660'],
      ['fr18', 'B. Guyenot, « Les tenues de combat de l’armée française 1964-2000 », reconstit.fr, 2020（收藏者文章）', ''],
      ['fr19', 'Armée de Terre 官方 Facebook, « #AvezVousConnu le treillis “Satin 300 modèle F1” ? »（仅见标题）', ''],
      ['fr20', 'État-major des armées, « Le nouveau camouflage de la tenue de combat : le bariolage multi-environnement », 2022-05-12', 'https://www.defense.gouv.fr/ema/actualites/nouveau-camouflage-tenue-combat-bariolage-multi-environnement'],
      ['fr21', 'Zone Militaire / opex360, « Le système FELIN entre en service », 2010-05-28', ''],
      ['fr22', 'Service du commissariat des armées, « Le nouveau bariolage multi-environnement arrive dans les unités ! », 2024-12-16', ''],
      ['fr23', 'Armée de Terre, « Le treillis BME (bariolage multi-environnement) »', 'https://www.defense.gouv.fr/terre'],
      ['fr24', 'Imperial War Museums, « smock, camouflage (Portuguese, ‘Lizard’ Pattern) »', 'https://www.iwm.org.uk/collections/item/object/30100409'],
      ['fr25', 'État-major de l’armée de Terre, Instruction n° 10300 relative aux tenues et uniformes…（2005 版）', 'https://www.legifrance.gouv.fr/circulaire/id/19910'],
      ['fr27', 'Spotsylvania County Museum, « The Cutting Edge: French Influences in the U.S. Civil War »', 'https://www.spotsylvania.va.us/2636/The-Cutting-Edge']
    ]
    ,de: [
      ['de1', 'Wikipedia, “Pickelhaube”（引 1842-10-23 内阁令等，辅助）', 'https://en.wikipedia.org/wiki/Pickelhaube'],
      ['de2', 'Kölnisches Stadtmuseum, “Des Himmels modernste Blitze”（藏品专题：普鲁士尖顶盔）', 'https://www.koelnisches-stadtmuseum.de/en/sammlung/militaria/des-himmels-modernste-blitze/'],
      ['de3', 'Wikipedia, “Feldgrau”（引 Heer, The German Infantry 1871–1914；Mollo 1978，辅助）', 'https://en.wikipedia.org/wiki/Feldgrau'],
      ['de4', 'Vestes Bellica, „Die Einführung und Entwicklung der feldgrauen Uniform des deutschen Heeres (1907–18)“', 'https://www.vestes-bellica.com/de/schwerpunkte/erster-weltkrieg/die-feldgraue-uniform-des-deutschen-heeres-1915']
    ]
  };

  return { ERAS: ERAS, COUNTRIES: COUNTRIES, CATS: CATS, TAGS: TAGS, CELLS: CELLS, BUS: BUS, CARDS: CARDS, FLOWS: FLOWS, REFS: REFS };
})();
